### ISSUE TITLE
[BUG] When winning at Shooting Gallery, dialogue text is bugged

### ISSUE THREAD

**Issue by Thirteen1355** [Admentus64/Patcher64Plus-Tool#100]
**Description**
When winning at the Shooting Gallery, the owner of the gallery repeats the text you see before starting the game. 

**How to Reproduce**
Go to the Shooting Gallery in Hyrule Castle Town and win the Shooting Gallery game. 

**Expected behavior**
The text will cut off at "Here's a fantastic prize" and instead continue describing the game rules again. After this, the game proceeds as supposed. You obtain the Deku Seeds Bullet Bag. 

**Videos**
https://www.youtube.com/watch?v=jAFaKgsyCTg

**Log files**
[2023-10-18.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13033426/2023-10-18.log)

**Comment by Thirteen1355** [comment]
Literally the second after sending this, I noticed you can edit the titles of issues.

**Comment by Admentus64** [comment]
This is a different issue than https://github.com/Admentus64/Patcher64Plus-Tool/issues/99 ?

**Comment by Thirteen1355** [comment]
> This is a different issue than #99?
> 
> I suspect it might be either the Restore Text, Typo Fixes, Gold Skulltula or 2x Speed dialogue options. If this could get confirmed.

When removing the 2x speed dialogue option, the game freezes upon hitting the last Rupee in the gallery. I'll send a log once I've tested all four variations.

**Comment by Thirteen1355** [comment]
![Rom results](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/045581b7-afa1-4820-b91e-6a7b482cc0d6)

- Removing Gold Skulltula or Typo Fixes produces no change, so they're not the issue.
- Removing Restore Text fixes the issue altogether. 
- Removing the 2x Speed (changing it to 1x) makes the problem worse. A freeze happens upon hitting the final Rupee (similar to yesterday's issue with the outdated patcher, but freeze instead of crash) instead of the dialogue issue happening afterwards. 

**Log**
[2023-10-19.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13041245/2023-10-19.log)

**Comment by Admentus64** [comment]
Alright. Seems like Restore Text is to blame for it. I was already planing over hauling it later on. The overhaul might fix it.

**Comment by Admentus64** [comment]
Might have been fixed with v22.0.9. Should be tested.

**Comment by Admentus64** [comment]
Confirmed to be fixed. With the newly reworked Restore Text. Works with 2x Text Speed just to test it.
