### ISSUE TITLE
[BUG] Lulu's Diary softlock with "Restore Text" in Majora's Mask.

### ISSUE THREAD

**Issue by justheretogame** [Admentus64/Patcher64Plus-Tool#101]
**Description**
The game will softlock and prevent any actions when you read Lulu's Diary in Zora's Hall. You can still control Link and pause the game, but you cannot use items, interact with anything, or leave the room. The clock and C-buttons disappear from the HUD.

**How to Reproduce**
1. Tick "Restore Text" in the patcher.
2. Go to Zora's Hall.
3. Talk to the stalker outside of Lulu's Room, then enter her room.
4. Read Lulu's diary by the door.

**Expected behavior**
You read her diary, then leave the room or buy green potion from the Business Shrub.

**Screenshots**
![GLideN64_ZELDA_MAJORA'S_MASK_008](https://github.com/Admentus64/Patcher64Plus-Tool/assets/120299915/969b9bb6-f9a6-43f2-ad8e-0a73cc10ddc9)

**Log files**
[2023-10-22.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13069931/2023-10-22.log)

**Comment by Admentus64** [comment]
Fixed with hotfix 2.
