### ISSUE TITLE
on your “releases” page you've reverted back to “2022” for some reason.

### ISSUE THREAD

**Issue by nr1995** [Admentus64/Patcher64Plus-Tool#102]
title says it all

**Comment by nr1995** [comment]
> Uh ok.
> 
> Not sure if this needed a dedicated bug report, but I suppose I update the title.

I'm not that familiar with GitHub.  Don't know how else to contact someone.
You can go ahead and delete this issue now.

**Comment by Admentus64** [comment]
Through Discord.
