### ISSUE TITLE
[BUG] 'Crashing' and corrupting rom (Majora's Mask)

### ISSUE THREAD

**Issue by blightfuel** [Admentus64/Patcher64Plus-Tool#103]
While playing, the game will freeze and flicker to a black screen - this happens consistently when I try to put the fish into the marine biology lab, will softlock the game until it is reset, only to lose the last 45 minutes of gameplay despite saving seconds before it occurred.

This also happened while doing the dog race mini-game, music will continue playing but a static black screen is displayed and buttons do nothing
*should also note that save-states do not fix the issue and the screen still displays black while no music plays.

Then when trying to disable any/all patches to the rom, Patchertool will say the rom is invalid/corrupted.
This does not occur on the vanilla rom, only after using Patchertool.

If there was a physical crash report I could upload, I would

**Comment by Admentus64** [comment]
If the ROM is invalid then the ROM is invalid. Only validated Rev 0 US ROMs are accepted.

Log files are found within ..\Files\Logs.

Closing due to lack of info and attempting to patch a non-supported ROM.
