### ISSUE TITLE
[BUG]The HUD do not fade out when exiting an Area with OOT

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#110]
**Description**
When you play a patched **Rom**, the fade out effect that occurs with the **HUD** when exiting an area, do not work anymore. Instead, it lingers until the other map is loaded.

**How to Reproduce**
Simply patch a OOT **Rom** with **CodeHook** features enabled.

**Expected behavior**
To fade out normally when exiting an area, like in the vanilla game.

Here's the problem displayed in the screenshot : 
![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/57508851-bf27-4ea6-87cc-639b8bf71ee2)
Normally, the **HUD** should have faded out when leaving, but with the **CodeHook** features on, it stays here until you're on the next area.

**Comment by Admentus64** [comment]
Be more specific please.

**Comment by GoldenMariaNova** [comment]
> Be more specific please.

Generally, when you exit an **Area**, the **HUD** disappears with a fadeout effect. Now, this effect is gone, so even when it fades to black, it stays until the next map is loaded.

There's no suck problem in vanilla.

**Comment by Admentus64** [comment]
Hide HUD. Ok.

**Comment by Admentus64** [comment]
Fixed with v23.1.0.
