### ISSUE TITLE
[BUG]Corrupted texture in Hyrule Field when the Remove Owls option is activated (OOT)

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#111]
**Description**
Apparently, when the **"Remove Owls"** option is activated, this specific texture on the windows of the ranch at night, seems all garbled and corrupted. There's a screenshot : 
![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/b877a6f4-252f-4ec8-b607-ce60ac520f51)

**How to Reproduce**
Simply enable the aforementioned option.

**Expected behavior**
It supposed to looks like this : 
![GLideN64_THE_LEGEND_OF_ZELDA_001](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/92918538-d2d7-4e1f-a46f-0ecc7c846bdd)

**Extras Notes**
If you want to know, it is all executed and shown with the same settings and emulator. I made sure it was not a emulator bug. 

If I can take a guess, it's probably because, since the **Owls** actors are shifted and removed, it also change how certain maps load their textures too, thus changed the offsets of this very specific one, since the **Owl** actor is gone. It also seems to do that only there, as there's no other maps using this texture.

So the solution would be : Change how the **Owls** are shifted when removed, or patch the texture in its new offsets. It's really up to you, though. There's it is if interested : ![THE LEGEND OF ZELDA#AE66800E#3#1_all](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/431cb481-2f60-4447-a874-6834db8d351a) (Just click the empty space between the two sentences right here).

**Comment by Admentus64** [comment]
In which order actors are shifted has no effect. The owl itself has nothing to do with this. It could be any actor or object you add or remove, and it would result in the same issue.

It's likely an issue with some of the VTX display list offsets not being shifted accordingly with the new actor list and object list sizes.

Adjusting the Scene Editor is tricky. It's extremely prone to breaking if mistuned.

Will look into it eventually.

**Comment by Admentus64** [comment]
Fixed with v23.0.4
