### ISSUE TITLE
[BUG]A very strange bug at Lake Hylia (As a child)

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#116]
**Description**
There's some strange bug happening when you go around or on the central isle (with the big tree), that makes the **Water Temple**'s gate opens by itself without touching anything... It's not harmful or anything, just strange... Why is that?

**How to Reproduce**
Well, just patch a Rom with any options selected.

**Expected behavior**
To not do that. It supposed to opens only as a adult and by a switch, activated by the **Hookshot**.

Is this because of the **Scene Editor**? Just a guess.

**Comment by Admentus64** [comment]
I am afraid I am going to have to close this issue if there's no concrete information on used options.

**Comment by Admentus64** [comment]
Closed due to lack of required information. Will reopen once required information gets posted in here.

**Comment by GoldenMariaNova** [comment]
> snips

Well, if it's the case, that also means it patches it to regular **OOT**, which admittedly is not a bug, but a feature... wrongly patched in vanilla redux. Maybe.

No, I didn't tried **Child Quest Classic** yet, just vanilla. That's why I thought it was a bug first.

**Comment by Admentus64** [comment]
Child Quest isn't patched when patching regular OoT. Child Quest modifications aren't even loaded in when selecting regular OoT. It is it's own script mode.

**Comment by GoldenMariaNova** [comment]
> snips

Turn out, it was a borked, crappy .sra file. Checked out with the debug, all is well.

I truly apologize for that. I have nothing else to say.
