### ISSUE TITLE
[FEATURE] An proposed improved moon texture for OOT

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#118]
I had an idea while trying **Gold Quest**: Why not improving the **OOT**'s moon? Along its many assets, this one was a good idea.

Basically, the original moon looks hastily made : 
![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/506c0778-ebd9-4370-a791-48c6b61c4e28)

But I don't want to rip the one in **Gold Quest**, so I made one that looks like this :
![GLideN64_THE_LEGEND_OF_ZELDA_002](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/5aeff8f8-f032-4231-a770-04cd55a8d192)

![GLideN64_THE_LEGEND_OF_ZELDA_001](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/5db83dbc-617e-4b8c-83ad-2a57a83ed6f1)

It respect the vanilla textures quality and have a stock resource feel to it, but still blends well.
It should be a simple graphic checkbox in the first category, well... **Graphics**.

Well, if you do something with it, there : https://drive.google.com/file/d/10tIwxkeSABkLC69OaWHUTSPh0_VATHL_/view?usp=drive_link

That's all for now.

**Comment by Admentus64** [comment]
Looks really nice.

Eventually:tm:

**Comment by Admentus64** [comment]
To be included with v23.2.0.
