### ISSUE TITLE
OoT "2x Text Speed" option not working

### ISSUE THREAD

**Issue by radiyodi** [Admentus64/Patcher64Plus-Tool#12]
Hi!

I recently tried using this tool to apply the "2x Text Speed" option for Ocarina of Time, but it doesn't seem to do anything when patching ("3x Text Speed" did work, however). For reference, I'm running `Patcher64+ Tool.ps1` directly with PowerShell instead of using the included .exe from the release.

I was able to get it working by modifying `Ocarina.psm1` at line 562:
```if (IsChecked $Redux.TextSpeed2x)```

Changing `TextSpeed2x` to `Text.Speed2x` let the option apply correctly for me.

**Comment by Admentus64** [comment]
Thanks for pointing this out. Should be fixed with v11.2.1.
