### ISSUE TITLE
[BUG] Star Road patch not detected

### ISSUE THREAD

**Issue by ensapra** [Admentus64/Patcher64Plus-Tool#120]
**Description**
Some patches for N64 return failed, could not find file

**How to Reproduce**
Open Patcher, select mario 64, try patching star road, and it will return failed

**Expected behavior**
Should patch 

**Screenshots**
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/61149758/586a38e7-c8a5-47f4-a8de-ed76bb1c60fa)

**Log files**
[2023-12-29.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13795789/2023-12-29.log)

**Comment by Admentus64** [comment]
Looks legit. Will look into it eventually.

**Comment by Admentus64** [comment]
Fixed with v23.1.1 - hotfix 2

Typo since v22.
