### ISSUE TITLE
[BUG] Virtual Console wad ports of NES The Legend of Zelda & Zelda II: The Adventue of Link don't work for anything.

### ISSUE THREAD

**Issue by RadicalDreamer286** [Admentus64/Patcher64Plus-Tool#121]
**Description**
Any attempts to patch, extract, inject, ect leads to a bad rom error.

**How to Reproduce**
Just try to use either game wad will lead to the result.

**Expected behavior**
Should have been able to at least patch the redux versions onto the wad. (The normal roms still work.)

**Screenshots**
![Capture](https://github.com/Admentus64/Patcher64Plus-Tool/assets/155194101/159dfe9f-ee49-4d6f-881d-23da5e227848)

**Log files**
[2023-12-29.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13795910/2023-12-29.log)

**Comment by Admentus64** [comment]
Looks legit. Will look into it eventually.

**Comment by Admentus64** [comment]
Fixed with v23.2.1 hotfix, although patched WAD of The Legend of Zelda won't boot. Separate issue to remove the game from Wii VC mode altogther.
