### ISSUE TITLE
[FEATURE] Something about the Master Quest's Water Temple...

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#123]
**Is your feature request related to a problem? Please describe.**

Well, a error do occurs when you rise the dragon heads before the mirage room, as documented here : https://tcrf.net/The_Legend_of_Zelda:_Ocarina_of_Time_Master_Quest

It makes one of the key in there completely useless and was fixed in the **3DS** version.

So, is there a way to fix the affected bit of memory in the original, or anything else?

That's just a proposal, of course.

**Comment by Admentus64** [comment]
I believe that's a bug part of the original N64 game.

**Comment by GoldenMariaNova** [comment]
> I believe that's a bug part of the original N64 game.

I know. I just wanted to know if it's fixable.

**Comment by Admentus64** [comment]
With the Scene Editor probably yes.

**Comment by GoldenMariaNova** [comment]
> snips

So, basically, it could be in **MQ.psm1**, fixing the wrong byte automatically every time the **Master Quest** _Water Temple_ is patched.

**Comment by Admentus64** [comment]
Maybe users don't want it always fixed.

It should be optional.

**Comment by GoldenMariaNova** [comment]
> snips

Fair enough.

**Comment by Admentus64** [comment]
Eventually :tm:

**Comment by Admentus64** [comment]
Included with v23.2.0.
