### ISSUE TITLE
[FEATURE] A little further improvement for the MM-Style menu

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#124]
After the alpha fixes got added, I thought I would improve the menu further (as handmade **Digital** and assets **Art** practice) to looks better and even more like **MM**,
so : 

**_Equipment menu_** : 
![equipment](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/14b6e7ed-d983-41f6-bb4d-2557c3e7d201)

**_Quest menu_** : 
![quest](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/7682c95d-7aa3-4913-9b69-e53dca1be7f5)

**_Map menu_** : 
![map](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/26c5d62d-fbaa-45a8-9539-546ceeaa1b83)

Basically, these three got some little pixel corrections, the two of them got the bottom-right borders remade to looks like the other ones, thus making it consistant. (It his kind of jarring to having two menus having different borders, making it looks like a hackjob.)

The **Quest** one, especially, got little details added (the faux-descriptions that **MM** had in his own menu), making it more accurate to this style.

All you have to do, is to replace the current **mm_pause_screen.ppf**, with the one in the **GD** Link below : 
https://drive.google.com/file/d/125qPMpXh__4GidErzAxwcVHcbE3ulv3t/view?usp=sharing

Also, as a side-note, The **L Button** Option background is still grey... is there a way to make it gold like the rest of the entire menu?

**Comment by Admentus64** [comment]
Not sure how differently it looks, but I suppose the original injects could be flawed. I'm not too versed in how it looks.

Eventually:tm:

**Comment by GoldenMariaNova** [comment]
> snips

There's one image for reference : 
![721d9512721385354f6b8ed7a3735a1f-mm_style_menus](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/9d3a7bd5-0f3d-41e8-b5c0-243e609da9bc)

As you see, the **Equipment** and **Quest** menus, have borders that are too bright, the former having smudges here and there and the latter lacking some details. The rest is perfectly fine though.

As for the **QUEST STATUS** "details", here's **MM**'s one to compare: 
![mm-completed-majoras-mask-100-on-switch-v0-583nk6npjhm81](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/0f281230-e7f4-4934-9d79-9ef4a7c82f5e)

So, it's just a little finalization of the **MM**-Style concept. That's it.
After that, it's pretty much finished.

**Comment by Admentus64** [comment]
Ghostly didn't make it. Only turned it into an patched and added it cus I was too lazy to do it back then.

**Comment by GoldenMariaNova** [comment]
> snips

Oh. Ok, then.

**Comment by GoldenMariaNova** [comment]
> snips

Do this feature request still stand tho?

**Comment by Admentus64** [comment]
Eventually :tm:

There's no reason to close down the issue. If it didn't stand I would had close it already.

**Comment by GoldenMariaNova** [comment]
> snips

Just as a update, the **Equipment** Screen is now even more faithful of what **Nintendo** should have done. 

The _**Character Display**_ is now encased, like the other frames.

Just to say, if you downloaded the file, you should do it again. Otherwise, dismiss this last warning.

**Comment by GoldenMariaNova** [comment]
> snips

I am absolutely sorry to bother you with this again : 

Apparently, the **Map** menu got it's slew of bad patterns and a untextured line. Fixed now.

The only one untouched is the **Items** menu now. 
Same advice as the post before.

**Comment by GoldenMariaNova** [comment]
> snips

I am absolutely sorry to bother you with this again : 

Apparently, the **Map** menu got it's slew of bad patterns and a untextured line. Fixed now.

The only one untouched is the **Items** menu now. It do not needs it.

Same advice as the post before.

**Comment by GoldenMariaNova** [comment]
Update : I created a new **mm_pause_screen.pff** to use. It have been tested and works perfectly.

Just replace the one you have, with the one in the same **Google Drive** link up there. 

That's it.

**Comment by Admentus64** [comment]
I try it out later, and merge it once I've seen it.

**Comment by Admentus64** [comment]
So the new .ppf patch is 6 kB larger, which seems fine.

Could you make a Pull Request for this instead since you already made the .ppf for it?

**Comment by GoldenMariaNova** [comment]
> snips

Done. Check your pull requests.

**Comment by Admentus64** [comment]
Merged. Closing this now since it has been completed.
