### ISSUE TITLE
[FEATURE] OoT: edit recovery from unbottled fairies or disable them altogether

### ISSUE THREAD

**Issue by ronin9208** [Admentus64/Patcher64Plus-Tool#125]
**Is your feature request related to a problem? Please describe.**
I really enjoy the challenge "no recovery heart drops" adds but, at least in Master Quest, random fairies drop from pots very frequently that it defeats the purpose of the challenge. Currently, there is only an option to edit the recovery rate of bottled/revive fairies, but not fairies just floating around. Of course, I could just avoid running into them, but sometimes this happens on accident. 

**Describe the solution you'd like**
An option to set the recovery of unbottled fairies just like we can with bottled/revive fairies (in my case, to zero).

**Describe alternatives you've considered**
An option to disable fairies from spawning from pots. Perhaps the "Item Drops" option in Hero Mode can have a "No Hearts + No Fairies" option. If this would disable fairies from even appearing in Fairy Fountains, while unintended, I think it would be worth it since fairies can still be bought in shops.

If all the above is not possible for technical reasons, perhaps an option to set the recovery to a flat low number, like 4.

**Comment by Admentus64** [comment]
Eventually :tm:

**Comment by GoldenMariaNova** [comment]
> snips

The best should be able to deactivate them in **dungeons** only, unlike **hearts** that can be safely removed everywhere (apart from shops).

Otherwise, it would broke the game balance. The fountains should be untouched at least.

**Comment by Admentus64** [comment]
A Recovery value setting would work here, just like the other existing options.

The scene editor could also be used to remove the jars and actors that spawn a fairy. That, or the code that spawns fairies from these actors has to be disabled.

**Comment by Admentus64** [comment]
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/099122cd-a331-4ca9-b8fa-3b9ba9cd721b)

I came up with this. Removing Flexible Drops. A Fixed Item Drop which has a Flexible Item (like a Jar) always drops a Fairy if the flag isn't set yet (leave the scene to reset the flag), and then drops a regular Flexible Drop. There's also the Random Item Drop in which the Flexible Item is just the Flexible Item.

How flexible items work depending on your current conditions, and follows a priority list:
* If you have <= 1 heart it becomes a fairy
* else if 1 < hearts <= 3 it becomes three hearts, or triple green Rupee if at max health
* else if 3 < hearts <= 5 it becomes a single heart, or green Rupee if at max health
* if you don't have magic, it skips past the MP check
* else if you have 0 MP it becomes a Large Magic Jar
* else if you are child and you have <= 5 seeds it becomes Deku Seeds (5), or nothing without a slingshot
* else if you are adult and you have <= 5 arrows it becomes a large arrow bundle (10), or nothing without a bow
* else if you have <= 5 bombs it becomes bombs (5), or nothing without a bomb item
* else if you have <= 10 Rupees it becomes a red Rupee
* else it becomes nothing

**Comment by Admentus64** [comment]
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/28403ee7-c411-4f01-a76e-d4392a6f4120)
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/14b7db09-424b-4271-990f-184dc089e925)

So ok. Recovery Value for touching fairies, and instead of completely removing the Flexible Item Drop it only removes the Fairy from it. That means the first time you break open a Fixed Item Drop that has a Flexible Item that it drops nothing. Or so I think. That's only some jars. This could however be completely addressed be redoing all jars with the Scene Editor that have a Flexible Item drop.

**Comment by Admentus64** [comment]
Added with v23.2.1.
