### ISSUE TITLE
[BUG]The HUD do not fade out when exiting an Cavern/Hole

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#127]
**Description**
Remember https://github.com/Admentus64/Patcher64Plus-Tool/issues/110, when I reported the bug about the **HUD** not fading out correctly when switching maps? It was fixed back then.

Well, the problem still persist in caverns, when exiting.

**How to Reproduce**
Simply go into a cavern an then exit.

**Expected behavior**
To do the same effect when exiting maps.

**Screenshots**
Going into a _cavern/hole_ : 
![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/5a35f25b-aaf6-485b-805f-348b306becb1)

Exiting the _cavern/hole_ : 
![GLideN64_THE_LEGEND_OF_ZELDA_001](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/398481e1-ea27-4f63-9257-00777b767e7d)

**Comment by Admentus64** [comment]
Try again with v23.2.1 hotfix 1.
