### ISSUE TITLE
[FEATURE]Borderless MM Hud Buttons for OOT (And MM too)

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#130]
Basically, all **MM** icons are **OOT** icons with a black borders around them... but the **MM** _HUD_ buttons don't have a borderless version of them.

I tried to do something with that, and this is the result : 
![GLideN64_THE_LEGEND_OF_ZELDA_001](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/f0513547-60de-4f43-94f8-b716b321c3a8)
![GLideN64_THE_LEGEND_OF_ZELDA_002](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/3da3c9ed-e55b-4fde-ab70-b1b8a5bb1d56)
_All tested on a clean **OOT** ROM_.

**Additional context**
I did this because I like the **MM** buttons, but hate the black borders around it. 
Since there's no equivalent nor anybody though about this, I made it.

Also as a bonus, these **MM** buttons will looks smoother in the eponymous game too.
So, it should be for both **OOT** and **MM**. Very simple.

Here's the drive link : https://drive.google.com/file/d/12ocvNexJ9cxVPkoWF76NGuv1eQfTlsOQ/view?usp=drive_link

Also, as a preview : 
The **button** - ![THE LEGEND OF ZELDA#E97A876F#3#1_all](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/a09d955f-0162-44b6-b55f-03e3b33ee56b)
The **patcher preview** - ![Borderless MM](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/755e6ccb-799a-4e77-aaa2-286c0d16b9f4)

The name of this should be : **Majora's mask** (Borderless)

So, that's all for now.

**Comment by Admentus64** [comment]
Looks good enough.

Eventually :tm:

**Comment by Admentus64** [comment]
Closing since it's merged now. Job well done.
