### ISSUE TITLE
[BUG] Majora's Mask "No Hearts" option behaves unintuitively

### ISSUE THREAD

**Issue by SSM240** [Admentus64/Patcher64Plus-Tool#131]
**Description**
In vanilla, heart drops will drop hearts when your health is full, and rupees when you're missing health. The "Item Drops: No Hearts" option, instead of simply removing heart drops, actually seems to behave inversely to vanilla: you get hearts when your health is full, and rupees when you're missing health. While this does succeed in not letting you restore health as easily, it also makes it harder to collect rupees when your health is full.

**Expected behavior**
I would expect this to consistently make these drops give green rupees, or possibly drop nothing at all when your health isn't full. The behavior of only giving hearts while full health is unintuitive to me.

**Video**
Here's a short clip that shows the behavior on a ROM with only the "No Hearts" patch applied and no other options enabled (recorded in RetroArch with the Mupen64Plus core): https://www.youtube.com/watch?v=T70tiqVpAY0

**Log file**
Here is the log file from when this ROM was generated:
[2024-01-27 trimmed.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/14074720/2024-01-27.trimmed.log)

**Comment by Admentus64** [comment]
Fixed with v23.2.2 - hotfix 2.
