### ISSUE TITLE
[FEATURE] Document what MM "Correct Rupee Colors" actually does

### ISSUE THREAD

**Issue by crozone** [Admentus64/Patcher64Plus-Tool#132]
Add tooltip help for the "Correct Rupee Colors" MM patch.

https://github.com/Admentus64/Patcher64Plus-Tool/blob/d7bd127f4ca26fa4c431cfa9a9a5584ae88b7db0/Files/Scripts/Options/Majora's%20Mask.psm1#L149-L152

There doesn't appear to be any documentation as to what this patch actually does - @GhostlyDark could you please assist?

**Comment by Admentus64** [comment]
I don't see how this is either an enhancement or bug. Option has a tooltip. Closing.

**Comment by crozone** [comment]
@GhostlyDark Thank you very much for the explanation. Given this, I think a better tooltip text may be "Corrects the color palette for the in-game Purple (50) and Golden (200) Rupee textures. In the base game they are closer to pink and orange, this changes them to more closely match their 3D chest item models."

Would you mind if I submitted a PR?
