### ISSUE TITLE
[FEATURE] Add MM dialog translations for English PAL and English Gamecube

### ISSUE THREAD

**Issue by crozone** [Admentus64/Patcher64Plus-Tool#136]
**Is your feature request related to a problem? Please describe.**

Currently there is only "English (default)" and "Restore Text" options for overhauling the English dialogue for the US Rev 0 MM ROM.

**Describe the solution you'd like**

Add additional dialog translations which use the PAL English translation (which was localized for the UK and Australia), as well as the GC English translation (which was localized for the USA).

These translations also already have fixed text commands.

**Describe alternatives you've considered**

Manually extract the script from the MM PAL and MM GC ROMs and use Patcher64+ to patch them into the US Rev 0 ROM

**Comment by Admentus64** [comment]
Only Rev0 US will be supported.

I am not going to support anything other than Rev0. So if anyone has any desire for it to happen they will be to submit a PR themselves.

I leave it open for the time being if there's any interest for others to tackle this.

**Comment by crozone** [comment]
The "Restore Text" option is a fan-made patch for the US Rev 0 ROM that doesn't quite match any of the official translations. It's a good patch, but it's not an official translation.

Reference for the "Restore Text" patch:

https://github.com/Admentus64/Patcher64Plus-Tool/blob/663686934e909caee506f5cde3b86ad36d8aba8e/Files/Scripts/Options/Majora's%20Mask.psm1#L1264-L1332

This feature request would specifically involve adding additional translations for a complete dialog replacement, to allow the US Rev 0 ROM to match the English PAL or English GC localizations verbatim. The use-case is mostly for people who prefer either the PAL or GC localisations, since the PAL localization is tailored for British English, and the GC localization is the most official final translation that is tailored towards US English.

Some of these differences are documented here:

https://tcrf.net/The_Legend_of_Zelda:_Majora%27s_Mask/Program_Revision_Differences#Text_Changes

I'd be happy to tackle adding this feature and create a PR, if you'd be okay with it.

**Comment by Admentus64** [comment]
Is there still an interest in doing this PR or can I go ahead and close this issue?

**Comment by crozone** [comment]
I'm still working on it but didn't get very far. Feel free to close if you like.

**Comment by Admentus64** [comment]
Oh ok. I have no need to close it if are still interested in doing it. Only wanted to know if you were interested in doing it.There is no deadline or anything you have to abide by. But since you offered to take up this issue it makes sense to only keep this issue open as long feel like you want to work on it.

If you need some help on how to get the code to work, feel free to reach out on my Mod64+ Discord server: https://discord.gg/P22GGzz, which would be a much easier way to discuss any questions on where you might have gotten stuck.

**Comment by Admentus64** [comment]
Closed due to inactivity.
