### ISSUE TITLE
inverse aim option cant work(OoT)

### ISSUE THREAD

**Issue by cloudywu44** [Admentus64/Patcher64Plus-Tool#142]
I patch the n64  Ocarina of Time  rom with lasted patch, but the inverse aim feature is useless: When I press down button,Link still look upward.
Please fix it,thank you.

**Comment by Admentus64** [comment]
Already fixed for v24.4.0 a while ago.

**Comment by cloudywu44** [comment]
I can find v23.3.5 only, Could u post the v24.4.0 ? thank you

**Comment by Admentus64** [comment]
v24.4.0 is WIP Early Access Patreon only for the time being. It will be made public when it's ready.

**Comment by Admentus64** [comment]
Fixed with v23.4.0.

**Comment by cloudywu44** [comment]
Thanks🥹從我的iPhone傳送Admentus ***@***.***>於2024年5月2日 上午5:44寫道：﻿
Fixed with v23.4.0.
