### ISSUE TITLE
[FEATURE] Option to change graphics of N64 Logo from boot intro to those from later version

### ISSUE THREAD

**Issue by Daddu3** [Admentus64/Patcher64Plus-Tool#143]
**Is your feature request related to a problem? Please describe.**

This definitely will come off as nitpicky but it always bugged me that N64-logo during boot of OOT Redux,  the 1.0-one, can't be changed to the more glossier version from later revisions that I grew up with:

 
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/53014019/e67cae8b-cfbd-4302-92ed-b06bbd62feb5)

**Describe the solution you'd like**

An option to choose between 1.0 or 1.1-logo in  the Graphics-tab for OOT Redux?

**Additional context**
I'm also wondering if this is a matter of being hardcoded or otherwise difficult thing to change due being based on 1.0 version, hence why it's not been explored before.

**Comment by Admentus64** [comment]
Not going to do this myself, but I am open for others making a Pull Request for it.
