### ISSUE TITLE
[FEATURE] Save where you left off using EntranceID instead of spawning you to TOT or Link's House depending on age.

### ISSUE THREAD

**Issue by BeezBumba** [Admentus64/Patcher64Plus-Tool#144]
**Is your feature request related to a problem? Please describe.**
There is no problem. It's more like a Quality of Life change and a timesaver.

**Describe the solution you'd like**
So lets say you exited kakiriko village and went to death mountain, when you save there and come back to your save, you would start at the same entrance you saved from (Which in this case is Death mountain).

**Describe alternatives you've considered**

**Additional context**

**Comment by BeezBumba** [comment]
Dang, im sorry i think it's already a thing i see it now Resume From Last Area. Sorry if you got a email.

**Comment by Admentus64** [comment]
Closing since request was already completed.
