### ISSUE TITLE
Request: Debug movement for the normal Zelda ROMs?

### ISSUE THREAD

**Issue by 60fpshacksrock** [Admentus64/Patcher64Plus-Tool#15]
Would it be possible to add a patch for the the debug movement into the normal
Ocarina and Majora's Mask? 
Also if possible, debug movement on Ocarina without requiring the expansion pack?

**Comment by Admentus64** [comment]
I dunno. Most likely not.

If there exists a GameShark or Action Replay code for it then I might be able to port it into the ROM... Or not. It's even better if there already exists a ROM patch for it or documentation on how to alter it in the ROM.

I am going to assume here neither of these exists, so I'll be closing this issue.

**Comment by 60fpshacksrock** [comment]
Okaay. Thanks anyway.
By the way, thanks for adding back an exe file, it works on Windows 7. I really appreciate it.
