### ISSUE TITLE
Missing one last thing...

### ISSUE THREAD

**Issue by stripes-8** [Admentus64/Patcher64Plus-Tool#155]
You have a very good collection of patches here, but I did notice it was missing the recent-ish [Ultimate Trial](https://www.romhacking.net/hacks/8640/) patch, which is apparently a very impressive hack!
It's not really an issue, I just thought it was the sort of patch you might want to include.
Anyways, I really like the work you've done with this, so good job with everything!

**Comment by Admentus64** [comment]
Sadly we are not going to include Ultimate Trial.

a) It's made with the debug decomp without any regard for Rev0 shifting compatibility, so you shouldn't expect any optional customization making it's inclusion kinda pointless.
b) The patch size is huge. Even targeting decompressed OoT GC MQ Debug (PAL). Which means a lot longer download times. We prefer to include ROM hacks which are well optimized (or can be optimized).

Closing for these reasons.

Thanks for liking the patcher anyway!

**Comment by stripes-8** [comment]
Yes, that makes sense. Oh well!
