### ISSUE TITLE
[BUG] Edited Wii WADs not showing up in Wii menu

### ISSUE THREAD

**Issue by TheFireHedgie** [Admentus64/Patcher64Plus-Tool#161]
I have here a North American WAD of both OOT and MM. They play very fine on my Wii. Then, I heard of your tool. When I saw all the changes that could be done either to the N64 ROM or the Wii VC Wad, you bet I was happy. When I loaded my OOT WAD to edit it, I chose "Ocarina of Time" in the games'l list. There's also a "Redux" check box near it, but since I had no need for "redux", I unchecked it. After applying a few patches such as skipping stealth missions (I tend to get a bit too nervous to do it very well...), a new WAD file was exported. So I installed the WAD on my 2nd Wii which didn't had any games yet, but... it's not showing in the Wii menu... nothing, as if I didn't do a thing. I use WiiMod Lite Manager to install the WADs and I use the latest version of your software. Both my Wiis are 4.3U native and have Homebrew. If you have more questions about my problem, feel free to reply :)

**Comment by Admentus64** [comment]
I recommend disabling all Wii VC channel changes when playing on a real Wii. To permanently disable channel changes check out the Options submenu (see screenshot)
![image](https://github.com/user-attachments/assets/1230298e-a4c3-49d5-80b5-68a82007b022)

Debug Settings -> No Channel Title Change
Debug Settings -> No Channel ID Change

Further support can be asked in https://discord.gg/P22GGzz

**Comment by TheFireHedgie** [comment]
> I recommend disabling all Wii VC channel changes when playing on a real Wii. To permanently disable channel changes check out the Options submenu (see screenshot) ![image](https://private-user-images.githubusercontent.com/8747034/381086371-1230298e-a4c3-49d5-80b5-68a82007b022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODM4NDEsIm5iZiI6MTczMDI4MzU0MSwicGF0aCI6Ii84NzQ3MDM0LzM4MTA4NjM3MS0xMjMwMjk4ZS1hNGMzLTQ5ZDUtODBiNS02OGE4MjAwN2IwMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTAxOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU4NzEyOGJjZWNiYWVlZTNjZWFhMjJjNWZlNmIzOGZkMTVmZmY4MTA1MjExYjEwZmMzNzI4ZTk5NzVjNGVlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dMPEM6-uvaA5j1s7MK9yXxlBvOvR9uAhtjGSylMcFyw)
> 
> Debug Settings -> No Channel Title Change Debug Settings -> No Channel ID Change
> 
> Further support can be asked in https://discord.gg/P22GGzz

Sorry for the late reply, I was busy yesterday. I did as the screenshot said, but the WADs became WAY TOO BIG for my Wii to handle both the patched OOT & MM games. When my Wii asked me to delete channels to make space, both channels were marked with a "?" instead of the official VC image and name... so I tried to do a much more simple test; patch the games in another language with nothing else checked. Same results, unfortunately... I might post screenshots later of what I mean. Meanwhile, I'll try to find the problem.

**Comment by Admentus64** [comment]
Did you perhaps left ROM decompression turned off?

The Wii VC can't handle decompressed ROMs in a WAD as those are too large in size. Patching Majora's Mask (even compressed) will always result in a larger WAD, but not as much as leaving the ROM decompressed.

**Comment by TheFireHedgie** [comment]
> Did you perhaps left ROM decompression turned off?
> 
> The Wii VC can't handle decompressed ROMs in a WAD as those are too large in size. Patching Majora's Mask (even compressed) will always result in a larger WAD, but not as much as leaving the ROM decompressed.
> 
> I didn't mean for you to copy over all settings. Only wanted to show you that the general options menu existed. You only need to enable those two options I mentioned yesterday.
> 
> You also might want to erase the previous channels and data first before trying out a new WAD. At least that's kinda a requirement when using Dolphin as to properly reset into the data from the new WAD.

Whoops! I was wrongfully doing as seen in the screenshot. I deleted all files and cache, then re-downloaded Patchet64+. Then I checked the two boxes you mentioned, and once exported, have a try on Dolphin. It worked! Now for step 2; test them on my Wii. Success! Thank you very much!

**Comment by Admentus64** [comment]
Closed since the issue seems resolved without the need for any fixes.
