### ISSUE TITLE
Added universal "Remove Filter" for all Wii VC WADs??

### ISSUE THREAD

**Issue by Nashismo** [Admentus64/Patcher64Plus-Tool#17]
Dear Admentus:

In the release Patcher64+ Tool v13.0.0, you stated:
"Added universal "Expand Memory" and "Remove Filter" for all Wii VC WADs"

I looked the entire Internet, and I found that you were the key to remove the horrible dark filter Nintendo used on the VC on the Wii. 

The problem is that this is not working for NES games, only on N64 wads you have the option to "choose" the removing of the filter. Do you think it could be possible to add this feature to NES wads?

You had given me a HUGE hope when you said UNIVERSAL and "for all Wii VC WADs" and thought this extended to NES games too.

Please I ask you to let me know if this could ever be possible,

My best regards and thanks.
Ignacio.

**Comment by Admentus64** [comment]
Hmm...

The dark filter overlay doesn't work quite the same on the NES on the VC as it does for the N64 on the VC.

I can assure you, it's pretty much "Universal" now with the changelog. I guess I should be more specific about it, but I am referring to the solution no longer being hardcoded. Thus can now be attempted for pretty much any title except for a few titles where it was hardcoded.

I disabled the removal of VC options for NES and SNES mode due it not doing that much. The same line for example used to disable the VC filter is indeed found in Super Mario Bros. (1) on the VC, except here it results too little when changed.

Closing this issue.

**Comment by Nashismo** [comment]
Could you give me a version on Patcher64 where this option is available then (for NES games)? You say it does not do much, but I want to see that with my own eyes.

If you can, thank you,
Ignacio.

**Comment by Admentus64** [comment]
You can change it in the Console.json file. But I wouldn't recommend doing it just now, there were a couple of bugs I found out when investigating this issue. So the next update should fix this (while VC patching in NES mode is still disabled).

**Comment by Nashismo** [comment]
Ok, sure as you said, it made no difference, the game looks the same (I tried Super Mario Bros 1 NTSC). And the home buttons stopped working.

Thank you for your time Admentus64, maybe in the future you could figure out how to remove this dark filter from NES wads, thank you anyhow.

**Comment by Admentus64** [comment]
Probably because of the bugs I mentioned, which will be fixed in the next update.

No plans for the forseeable future to further attempt to solve this issue. Not that don't I want to make this happen, but progress can't happen with new insights. Whenever it this issue will be solved remains to be seen.

**Comment by saulfabregwiivc** [comment]
For NES dark filter removal on Wii VC titles, it's not a dark filter that Nintendo put but a dark color palette (the NES itself didn't had a video decoder so it used the colors of the connected TV).
Maybe that is what you're looking for? https://gbatemp.net/threads/tutorial-replacing-the-nes-color-palette-in-wii-virtual-console-games.590714/
