### ISSUE TITLE
Majora's Mask Redux: Ocean Deed Side-Quest Impossbile to complete

### ISSUE THREAD

**Issue by marigi64** [Admentus64/Patcher64Plus-Tool#2]
For Majora's Mask Redux, I can't properly exchange the ocean deed for the Business Scrub's Deku Flower at Ikana Canyon. 

After he says "I'm not asking for it for free. I'll give you this!" The Ocean Deed is taken but the player isn't given anything along with Business Scrub remaining in the flower, softlocking the side-quest and preventing the player from getting the heart piece on the other side of the canyon. 

The only option I enabled for the patcher was enabling the D-pad Layout on the right side in the redux options.

**Comment by Admentus64** [comment]
Yup. This issue should be fixed with V7.6.0.

Just forgot to close it yesterday 😃
