### ISSUE TITLE
[INCOMPLETE] [Ocarina of Time] GC Scheme option not applied in certain text boxes

### ISSUE THREAD

**Issue by opsodps** [Admentus64/Patcher64Plus-Tool#21]
**Description**
With the GC Scheme option enabled, at least these three text boxes still have their original N64 text. This also might apply to other instances in the game, but I haven't found them yet.

Additional info: The original file I patched was revision 1.0 of Ocarina of Time, and I had both "Enable Options" and "Enable Redux" checked.

**How to Reproduce**
Interact to the NPCs/signs in Kokiri Forest in the attached screenshots.

**Expected behavior**
First screenshot: Should say "the + Control Pad" instead of "the [L]". See second screenshot for how it looks in the GameCube version.
Third and fourth screenshot: A button should be green.

**Screenshots**
![the_legend_of_zelda-001](https://user-images.githubusercontent.com/75006249/139119438-1c921a18-0441-4194-b88e-0bf848821aea.png)
![3](https://user-images.githubusercontent.com/75006249/139119465-c8223f16-8988-463d-8260-81092532b9aa.png)
![the_legend_of_zelda-002](https://user-images.githubusercontent.com/75006249/139119458-9bd89b9c-352d-485b-b018-f4fdd457524d.png)
![the_legend_of_zelda-000](https://user-images.githubusercontent.com/75006249/139125958-f1e597bc-ccf3-4732-8954-1949cfca9dd2.png)

Edit: This NPC mentions the A button four times, with the first three instances being blue and the last one being green.

![the_legend_of_zelda-003](https://user-images.githubusercontent.com/75006249/139160983-b6b37293-0a1d-41f9-99cb-91ed6fdce397.png)
![the_legend_of_zelda-004](https://user-images.githubusercontent.com/75006249/139160985-607caaed-775c-4f37-8759-829ab3dcce05.png)
![the_legend_of_zelda-005](https://user-images.githubusercontent.com/75006249/139160986-9d17faf5-abeb-4d2e-b975-8b1096c7d261.png)
![the_legend_of_zelda-006](https://user-images.githubusercontent.com/75006249/139160988-7ed1df1b-702e-4ac8-a583-06d1a68eb7f2.png)

Edit 2: One text box in the fishing pond:
![the_legend_of_zelda-007](https://user-images.githubusercontent.com/75006249/139540448-8f93a32f-de7e-4eb1-ae85-88e2940bb63c.png)

**Comment by opsodps** [comment]
Added another instance in the OP in case it was missed. Not sure if the fix would apply to all instances in the game or separately.

**Comment by Admentus64** [comment]
Thanks for mentioning this. The next update goes for a more universal solution, so these cases should be included now as well, but I should confirm this nevertheless. Your original cases were confirmed to be fixed though.

Also, this fix will come with v15.1.0 instead of v15.0.1 (with v15.1.0 being the next update instead).

**Comment by Admentus64** [comment]
Ok, I looked at your additional examples. I can confirm those are addressed for v15.1.0 as well.
