### ISSUE TITLE
Deblur Majoras Mask rom Hacks

### ISSUE THREAD

**Issue by Singledad7** [Admentus64/Patcher64Plus-Tool#22]
Could you implement deblur for the 2 Rom Hacks Majoras Mask Masked Quest and Majoras Mask Master Quest

**Comment by Admentus64** [comment]
There's no support for "Additional Options" for these ROM hacks. It's easier to port over both ROM hacks to the regular Rev 0 instead. In fact, Master Quest is already ported to Rev 0 as an option in "Additional Options". From there, you can also select and combine all other options such as "No Blur".

**Comment by Singledad7** [comment]
I dont see an advanced option tab? And when I pick Master Quest all tabs go awa
![NoAdvancedOptions](https://user-images.githubusercontent.com/21270740/144314720-d402963b-e2a2-4361-ba41-79b8776e2263.PNG)
y?

**Comment by Admentus64** [comment]
The "Majora's Mask: Master Quest" has no Additional Options like I stated before. Only the regular game does (first patch option), which has Master Quest backported.

**Comment by Singledad7** [comment]
Could you backport Masked Quest?

**Comment by Admentus64** [comment]
No plans at the moment.
