### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gengarm** [Admentus64/Patcher64Plus-Tool#23]
**Description**
Rom doesnt show up in the same directory, or anywhere for that matter.

**How to Reproduce**
Trying to patch MM

**Expected behavior**
A Patched Rom.

**Screenshots**

**Log files**
Please post a log file. You can find it in Files/Logs.

**Comment by Admentus64** [comment]
Patching works fine. Be more specific about what the problem is and under which conditions it exactly occurs in. Including the log file would help.
