### ISSUE TITLE
I dont see an advanced option tab? 

### ISSUE THREAD

**Issue by Singledad7** [Admentus64/Patcher64Plus-Tool#24]
I dont see an advanced option tab? And when I pick Master Quest all tabs go away.So theirs no way for me to do what you said in reponse to my inquiry today unless Im missing something.  "In fact, Master Quest is already ported to Rev 0 as an option in "Additional Options". From there, you can also select and combine all other options such as "No Blur"
![NoAdvancedOptions](https://user-images.githubusercontent.com/21270740/144315472-1b5334ea-6777-43ee-9c98-8d72ccdbf507.PNG)
.

**Comment by Admentus64** [comment]
Intended. No plans.

Only vanilla Majora's Mask has support for Additional Options.
