### ISSUE TITLE
[BUG] OOT Feminine animations do not get patched.

### ISSUE THREAD

**Issue by Captain-Undercooked** [Admentus64/Patcher64Plus-Tool#25]
**Description**
I have patched Ocarina of Time before, and only once have feminine animations been properly patched. On every other occasion, the character did link's standard idle animations.

**How to Reproduce**
Start Patcher64+, 
enable feminine animations,
patch the Rom,
play game and animations do not appear to have changed.

**Expected behavior**
I expected the Aria model to play the feminine idle animations.

**Log files**
[2021-12-18-23-26-35.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/7801514/2021-12-18-23-26-35.log)

**Comment by Admentus64** [comment]
Confirmed. I have it hotfixed in a few hours.
