### ISSUE TITLE
Bomb Upgrades Order Messed Up When Changing Max Capacity in OoT

### ISSUE THREAD

**Issue by XModxGodX** [Admentus64/Patcher64Plus-Tool#3]
When I change the max capacity of bombs to 30, 60, 99 like in Wind Waker the first bomb bag upgrade (which should be the big bomb bag) is changed to the biggest bomb bag. Changing any of the max bombs to other values also change it in other ways like getting a second big bomb bag instead of the biggest bomb bag. It only seems to happen with bombs for whatever reason every other upgrade works as intended. If I were to guess it has something to do with the association of bombs and bombchus.

**Comment by Admentus64** [comment]
Update v7.7.1 should hopefully end it by preventing the value 30 to be assigned to the base Bomb Bag value. For some reason which specific value causes the first Bomb Bag upgrade to get skipped. Trying to input 30 in the Patcher64+ GUI will now automatically change itself into 31 to prevent this issue.

Other values have been tested as well, and seem to cause no issue. So value like 25 or 35 work fine for example. Other capacity upgrades like the Bullet Bag don't seem to experience this issue (in which case if the base value would be increased to 40 to match the original value of the first upgrade).

It could be that the value 30 is used for the first Bomb Bag upgrade and setting this for the initial Bomb Bag as well causes some kind of confusion for the game.

Should the issue still occur, or with different values, please open another issue.
