### ISSUE TITLE
Redundant tooltip text for "Lives" under Super Mario 64

### ISSUE THREAD

**Issue by NintendoManiac64** [Admentus64/Patcher64Plus-Tool#35]
This is for N64 mode in Super Mario 64, but for all I know it may also exist with VC mode (I did not test that).

This exists in both v17.2.0 and v17.2.3.

![image](https://user-images.githubusercontent.com/11896003/158249400-af655754-a4c0-45aa-8579-804f9e10a552.png)

**Comment by Admentus64** [comment]
Will be fixed with the next update.
