### ISSUE TITLE
Request : help with translation of ootpc

### ISSUE THREAD

**Issue by RyzenDew** [Admentus64/Patcher64Plus-Tool#36]
can you do the Spanish Translation for this project https://github.com/blawar/ooot

**Comment by Admentus64** [comment]
Denied. We're not the PC port project.

**Comment by RyzenDew** [comment]
Imaging not helping … wow whatever

**Comment by Admentus64** [comment]
Wow, talk about being rude...

**Comment by GhostlyDark** [comment]
We don't speak Spanish and this isn't the place to ask for help for an unrelated project. There is nothing to discuss here.
