### ISSUE TITLE
Zelda 1 Animated Tiles results in broken ROM

### ISSUE THREAD

**Issue by Ritaku02** [Admentus64/Patcher64Plus-Tool#37]
I've tried in both Mesen (which is supposed to be a highly-accurate emulator) and the Everdrive N8 Pro, but Animated Tiles results in a ROM that just hangs on a black screen on startup.

Addendum; It happens when also patching in Link's Awakening GFX, without the LA GFX patch Animated Tiles works fine.

**Comment by Admentus64** [comment]
Will be looked into it later eventually. No ETA for now.

**Comment by GhostlyDark** [comment]
Confirmed. Link's Awakening GFX + Animated Tiles breaks the ROM.

**Comment by GhostlyDark** [comment]
Options aren't compatible, so only one of those can be selected at any time. 7b9001122966b526a0d27a3572d06b1c7bd8197d
Thank you for reporting the issue.
