### ISSUE TITLE
How do we update?

### ISSUE THREAD

**Issue by Nickelbawker** [Admentus64/Patcher64Plus-Tool#39]
Does the program just close when it finishes updating or am I experiencing a connection failure causing the update to close?

My patcher says its 18.0.0 & I ran the updater twice.

**Comment by Admentus64** [comment]
Share you log file please.

**Comment by Nickelbawker** [comment]
[2022-07-23.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9177477/2022-07-23.log)

[2022-07-22.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9177495/2022-07-22.log)

Super long logs, was testing out the tool a lot. Love it btw. Thank you.

**Comment by Admentus64** [comment]
There's a known issue that some users can't connect to the GitHub repo for the auto-updater. It shouldn't crash of course, but for the time being there's no known solution.

**Comment by Nickelbawker** [comment]
I just ran it for 19, it times out for the 19.01. In my case I would say definitely don't worry about it, I do want the update but my internet isn't really an ideal candidate to diagnose issues.

**Comment by Admentus64** [comment]
In case you want the GitHub you can just download the master instead:
https://github.com/Admentus64/Patcher64Plus-Tool/archive/refs/heads/master.zip

The auto-updater is nothing more than grabbing the latest files from the GitHub master.

**Comment by Admentus64** [comment]
Hopefully fixed as of v20.3.2.
