### ISSUE TITLE
Issue with Bomb Bag (1) Value Validation in Majora's Mask - Additional Options & Redux

### ISSUE THREAD

**Issue by tree-frog** [Admentus64/Patcher64Plus-Tool#40]
In version 19.0.0, in _Majora's Mask - Additional Options & Redux_, it currently appears impossible to set the Bomb Bag (1) capacity to "30", as the interface locks to "31" after pressing "3" on the keyboard.  Other upgrades and values do not show issues.

<img width="1173" alt="Screen Shot 2022-07-23 at 10 44 38 PM" src="https://user-images.githubusercontent.com/24217599/180630211-9010bcca-5f87-4ff6-ae9c-5e0a1407c6dc.png">

PS: Admentus - I cannot thank you enough for making this amazing tool. It's magical.

**Comment by Admentus64** [comment]
This is intended. Some values are prevented for the first bomb bag in OoT and MM as to prevent issues.

**Comment by tree-frog** [comment]
That makes sense. It's listed in the tooltips for OOT, but not MM, so I missed it on the first go-around. Thank you!
