### ISSUE TITLE
Feature Suggestion – GUI Indicator that Window is Updating

### ISSUE THREAD

**Issue by tree-frog** [Admentus64/Patcher64Plus-Tool#41]
Hi Admentus,

I just had one suggestion to make the GUI a little more obvious to newer users.

When switching the <Current Game Mode> or selected <Patch>, the GUI does not update until all of the options are loaded. For games with a lot of options (OOT/MM), this can take a while (long enough for Windows to display "Not Responding" in the window title). There's no feedback that this is what's happening, and newer users may not understand that this is how the program works.

It would be useful to have e.g. a status message or color change to mark the old window contents as stale, before blocking to load the new options (I'm hoping that is is feasible to do synchronously, as I imagine that an asynchronous indicator would require a substantial re-write or may be impossible here).

This obviously isn't a high-priority issue & doesn't affect functionality, but I just thought I would make the suggestion. Thanks again for all your amazing work on this project.

**Comment by Admentus64** [comment]
PowerShell is a linear script, so asynchronously scripting isn't exactly a thing.

**Comment by tree-frog** [comment]
This has been implemented in v20. Awesome! Thanks again for all the hard work.

**Comment by Admentus64** [comment]
Huh? I did?

**Comment by tree-frog** [comment]
Yes, hahaha.  The controls are disabled when changing ROMs, and there's a new status message. :-)

**Comment by Admentus64** [comment]
Must have forgotten about it then lol. One of those minor changes I forgot about.

**Comment by tree-frog** [comment]
I checked because of the following line in the release notes:
"Changed GUI to be locked when changing generating GUI options"

Which is exactly what this bug was about (only put more succinctly). Thanks again!
