### ISSUE TITLE
Feature Suggestion – OoT Master Quest support

### ISSUE THREAD

**Issue by nablak** [Admentus64/Patcher64Plus-Tool#42]
Considering that the Debug GC version of OoT MQ is already supported, would it be possible to support OoT MQ? (PAL/GC)

I would like to change the HUD colors back to N64 but I can't find a tool for that.

Thanks.

**Comment by Admentus64** [comment]
There are no plans to support other versions of OoT right now.

**Comment by nablak** [comment]
A solution was provided by ShadowOne333 in romhacking.net forum, quoted here: "[You can use an OoT v1.0 ROM with Patcher and convert it into a pseudo Master Quest ROM with no issues (I say pseudo because it's still v1.0 but with title screen, the colors of HUD stuff, messages and dungeons changed to match MQ), and you can also pick and choose if you want additional QoL features or not to go along with that.
That's one of the features I worked on.](https://www.romhacking.net/forum/index.php?topic=35406.0#:~:text=You%20can%20use,I%20worked%20on.)"

**Comment by nablak** [comment]
A solution was provided by ShadowOne333 in romhacking.net forum, quoted here: "[You can use an OoT v1.0 ROM with Patcher and convert it into a pseudo Master Quest ROM with no issues (I say pseudo because it's still v1.0 but with title screen, the colors of HUD stuff, messages and dungeons changed to match MQ), and you can also pick and choose if you want additional QoL features or not to go along with that.
That's one of the features I worked on.](https://www.romhacking.net/forum/index.php?topic=35406.0#:~:text=You%20can%20use,I%20worked%20on.)"

**Comment by Admentus64** [comment]
Don't double post.

Also, Master Quest has been include for over a year now. Please check the patcher on actual issues or missing features before reporting an issue. Don't label it as a bug either. Label it as a Feature Request.

Closed.
