### ISSUE TITLE
Feature Suggestion – Ocarina of Time @ 60 fps

### ISSUE THREAD

**Issue by nablak** [Admentus64/Patcher64Plus-Tool#43]
Is it possible to patch OoT to run @ 60 fps? Some time ago the idea was in progress: [](http://forum.pj64-emu.com/showpost.php?p=55223&postcount=2)

**Comment by Admentus64** [comment]
There were never plans for 60 FPS. Theoretically it's possible. It's just not worth it given the many issues it causes. Closing this issue.

**Comment by nablak** [comment]
Is this option already available (maybe I missed it) or will it be part of the new release?
