### ISSUE TITLE
[BUG] Majora's Mask Downgrade doesn't work

### ISSUE THREAD

**Issue by MoriyaFaith** [Admentus64/Patcher64Plus-Tool#44]
**Description**
The downgrade patches for Majora's Mask don't appear to work, causing the patched ROM to be 

**How to Reproduce**
Simply try to patch a Majora's Mask rom using the GameCube version at a base.

**Expected behavior**
The ROM is patched as intended, as a 32 MB file.

**Screenshots**
![image](https://user-images.githubusercontent.com/46070717/185033665-0508bc81-1141-4f44-b9c8-7485406f7a06.png)

**Log files**
This displays a log file that, on top of finding a couple invalid patches that can't be located(?), includes 2 seperate attempts to patch Majora's Mask with Redux and options. First, a failure with the GC rom, and then success with the same options on the N64 Version.
[2022-08-17.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9356284/2022-08-17.log)

**Comment by Admentus64** [comment]
Hmm... This seems to be both a case of downgrading and conversion. It's a .n64 ROM, which is Little Endian rather than Big Endian. It could either be the downgrading or conversion having some issues, I'll look into it later.

**Comment by Admentus64** [comment]
Should be fixed with v19.1.11 now.
