### ISSUE TITLE
[BUG] GC Collector's Edition Majora's Mask doesn't work with Redux or widescreen and does not downgrade

### ISSUE THREAD

**Issue by tjcouch1** [Admentus64/Patcher64Plus-Tool#48]
**Description**
Similarly to #13 and #44, it appears my Majora's Mask extracted from GC Collector's Edition is not running properly in this tool in some cases. The ROM itself works in emulators perfectly, but it seems the ROM does not work in the Patcher when checking Redux or Widescreen (Advanced).

My GC Collector's Edition OoT downgraded with [this downgrading tool](https://oot.flagrama.com/) worked perfectly! Thank you for all your hard work on this. Love this tool.

**How to Reproduce**
1. Extract Majora's Mask ROM from GC Collector's Edition by following the same steps as extracting the OoT ROM for [OoT Randomizer](https://wiki.ootrandomizer.com/index.php?title=Making_A_Backup#Extract_File_From_Disc).
2. Load the MM ROM into Patcher64+ Tool. (The Revision dropdown only shows Rev0 (US) - dunno if that's a problem)
3. Notice the "Downgrade" checkbox is not available. From its description in the ReadMe, I cannot tell if this is actually an issue. However, I would love to know how to patch my ROM into a true Rev0 ROM if possible.
4. Select patch options. Make sure to check Redux or Widescreen (Advanced). The handful of other options I tried seem to work like Pictobox fix and Extended Draw Distance.
5. Click Patch Selected Options. Notice that it seems to skip the "Compress Majora's Mask ROM" step in the status box.
6. Wait for a beeping noise to signal it is finished. The status box indicates it is finished as well.
7. Note that the ROM file generated (TJsMM_redux_patched.z64) is 0 KB and is completely empty.

**Expected behavior**
Patching Majora's Mask produces a ROM that functions.

**Screenshots**
Patcher64+ Tool appears to recognize my MM ROM just fine:
![image](https://user-images.githubusercontent.com/3528918/188326120-175b75a6-708b-45c8-ade2-90ef5fec286d.png)

After clicking Patch Selected Options and waiting for it to finish and beep:
![image](https://user-images.githubusercontent.com/3528918/188327657-242767fb-4831-4e74-9ca8-a6457d87e172.png)

**Log files**
Here's a log where I patched a bunch of different ways with varying success, all tied to Redux or Widescreen (Advanced).
[2022-09-04.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9485290/2022-09-04.log)

**Comment by Admentus64** [comment]
Should be fixed with v19.1.11 now.

**Comment by tjcouch1** [comment]
Awesome! Thank you very much! I don't suppose you have an estimate for when it will be released, do you?

**Comment by Admentus64** [comment]
It's already published 2 days ago. Just not repackaged as a Release.

**Comment by tjcouch1** [comment]
Thank you for letting me know! It works perfectly! I really appreciate your hard work on this. Have a great day!!
