### ISSUE TITLE
Ocarina of Time - Hylian Shield Texture Option Not Working Properly

### ISSUE THREAD

**Issue by shoguna** [Admentus64/Patcher64Plus-Tool#49]
**Description**
The Hylian Shield texture option does not properly patch in the texture of the shield.

**How to Reproduce**
Attempt to change the Hylian Shield texture.

**Expected behavior**
The texture of the shield should have changed but the texture remains the default Hylian Shield texture.

**Screenshots**
![image](https://user-images.githubusercontent.com/23407073/188806208-d33ee2b6-bac0-432e-857a-9da7eed314f1.png)

![image](https://user-images.githubusercontent.com/23407073/188807274-09e54b24-d46c-4f94-8829-51ef38856f59.png)

**Log files**
(It shows that only the Hylian Shield icon texture was replaced, nothing else.)

Found values at: 00FC59E0
00FC59E0 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Deku Shield\Wooden Shield.front
7FB000 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Deku Shield\Wooden Shield.icon
8AE400 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Deku Shield\Wooden Shield.en.label
7FC000 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Hylian Shield\Beta Shield (Alternative).icon
Found values at: 00F92280
00F92280 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Mirror Shield\Censored Mirror Shield.bin
1616000 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Mirror Shield\Censored Mirror Shield.chest
1456388 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Mirror Shield\Censored Mirror Shield.reflection
7FD000 -> Patch file from: C:\Users\asian\Desktop\Zelda 64 Modding\Patcher64+ Tool\Files\Games\Ocarina of Time\Textures\Equipment\Mirror Shield\Censored Mirror Shield.icon

**Comment by Admentus64** [comment]
Need more information. Was the Child model replaced?

**Comment by shoguna** [comment]
> 

I used the Dusk & Dawn Child model, although I don't think that would break the Hylian Shield texturing since vanilla child model shares the Hylian Shield texture with adult. And yeah, Adult model was not changed. I'll paste the full log below.

[2022-09-07.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9503673/2022-09-07.log)

**Comment by Admentus64** [comment]
Ok. That explains why. There's no bug then. It's simply disabled because a non-supported model was used. Closing this issue.

**Comment by shoguna** [comment]
And now I see why it was restricted in the first place.
![image](https://user-images.githubusercontent.com/23407073/188934984-d6641a21-a63f-4b9f-9606-294e1eb8b343.png)

**Comment by Admentus64** [comment]
Right ok. Still the D&D model? I do some more research on it, or otherwise restrict it back again.

**Comment by shoguna** [comment]
> Right ok. Still the D&D model? I do some more research on it, or otherwise restrict it back again.

Yep. Game crashed upon equipping Hylian Shield as child.
