### ISSUE TITLE
Can't Select or drag patch file

### ISSUE THREAD

**Issue by chemscobra** [Admentus64/Patcher64Plus-Tool#5]
after I load the rom for patching, I'm unable to select the patch file. The browse button is not working
![2020-11-21-15-49-11](https://user-images.githubusercontent.com/2581610/99885140-99b87180-2c11-11eb-880c-a20e674370a6.gif)

**Comment by Admentus64** [comment]
Thank you for the report. It's an indeed of v9.0.0 indeed. I push out a hotfix for it in the next 24 hours. Turns out I missed updating a simple reference.

**Comment by Admentus64** [comment]
Should be fixed now with v9.0.1. Let me know if it fixed your problem.
