### ISSUE TITLE
[BUG] Copying Files Softlock

### ISSUE THREAD

**Issue by Tetddg** [Admentus64/Patcher64Plus-Tool#52]
**Description**
It seems like if you enable redux using OOT 1.0 with additional options & redux, when choosing any file to copy, the game/menu will Softlock. it will still Softlock even if you enable redux and uncheck everything in selected options under redux tab. (Using the latest version - Patcher64+ Tool v19.1.7 (2022-08-31)

**Expected behavior**
Able to copy files in the file select menu of OOT redux.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/116306431/197034987-ad6e22a2-44c0-4b3c-9aab-ef0f6ff9b9a4.png)
![GLideN64_THE_LEGEND_OF_ZELDA_004](https://user-images.githubusercontent.com/116306431/197034988-811c455d-5296-4624-a41d-35d009e36caf.png)

**Log files**
[2022-10-20.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/9833171/2022-10-20.log)

**Comment by Admentus64** [comment]
v19.1.7 is outdated already. Try again with v19.2.1 (use auto-updater or grab from master directly: https://github.com/Admentus64/Patcher64Plus-Tool/archive/refs/heads/master.zip).
