### ISSUE TITLE
Feature request - invert camera controls while in first person

### ISSUE THREAD

**Issue by bosshunter** [Admentus64/Patcher64Plus-Tool#55]
Request for Ocarina of Time (maybe other games can apply).
Anyway to add an option to invert the vertical controls while in first person mode?
So, look up by pressing up and look down by pressing down.

**Comment by Admentus64** [comment]
Labels as enhancement. No plans. Won't happen likely.

**Comment by brad86m** [comment]
Still not planned ?

Personally, this would be a Godsend for me as I have a coordination issue due to a car accident many years ago. As easy as it should be to adjust to the inverted controls, it's sadly not possible any longer.

**Comment by Admentus64** [comment]
Will be added for OoT Redux with v20.1.0.

**Comment by Admentus64** [comment]
Completed with v20.1.0.

**Comment by amoliski** [comment]
Any chance of this being added to MM as well?

**Comment by Admentus64** [comment]
No plans as of now.
