### ISSUE TITLE
Wad's being broke when being patched with oot redux[BUG]

### ISSUE THREAD

**Issue by Jonblaze5** [Admentus64/Patcher64Plus-Tool#57]
**Description**
Yes it patched just fine but whenever I install the wad on my Wii it says installed but doesn't show on Wii menu and something with the program is breaking the new patched wad 
I've tried both game name and id off and on and still get the same result.
**How to Reproduce**
Just take the oot wad and patch it with redux and try to install on Wii and nothing shows up after saying successful install.

**Expected behavior**

**Screenshots**

**Log files**
Please post a log file. You can find it in Files/Logs.

**Comment by Admentus64** [comment]
Necessary info is missing. Please provide.

**Comment by Admentus64** [comment]
Closing this issue due to lack of info.

**Comment by gaben1488** [comment]
I have the same issue!

**Comment by Admentus64** [comment]
Start a new issue, and describe the issue properly.
