### ISSUE TITLE
[BUG] Majora's Mask | Can't Learn New Wave Bossa Nova

### ISSUE THREAD

**Issue by Onemario1234** [Admentus64/Patcher64Plus-Tool#58]
I honestly don't believe this is even the right place to report this, but I have literally no other option right now, unless I get redirected elsewhere (which, please do).

**Description**
The game, for some unknown reason, won't let me pull out the Zora Guitar in the Marine Research Lab, and because of that, I can't learn the New Wave Bossa Nova from the Zora tadpoles. Oddly, it's _only_ the Zora Guitar, and _only_ in the Research Lab. If I'm in any other form or location, it pulls the instrument out as expected.

**How to Reproduce**
I don't know of any other options that would interfere with this kind of thing, but I had Underwater Ocarina disabled by force since I had different Ocarina icons enabled. I also had the D-Pad functionality enabled.

**Expected behavior**
I expected Zora Link to be able to pull out the Zora Guitar no problem so I can properly learn the song.

**Screenshots**
(Notice how the Zora Guitar icons on both the C-Buttons and D-Pad are faded and unusable.)
![image](https://user-images.githubusercontent.com/25996506/204449844-b5b95b9a-62bc-4785-9d53-a273e735e0c1.png)

**Comment by Admentus64** [comment]
Update to version 19.2.1 first if you haven't already. This specific issue has been fixed since 19.1.8. Report back then again.

Please share all relevant info. Easiest would be to share the log file.

**Comment by Admentus64** [comment]
That's an one-time issue because you used the Ocarina Icons options before. Reset this once. The new update changed the coding for this feature, and icons are linked to your save data.

**Comment by Onemario1234** [comment]
How do I remap it again?

**Comment by Admentus64** [comment]
Open the pause screen. Place the cursor on the item. Press the D-Pad button you want it to map it to.

Only transformation masks and instruments work for now.

**Comment by Onemario1234** [comment]
... Huh. Didn't know I could do that.

Thanks! And sorry for the trouble!

**Comment by Admentus64** [comment]
No problem. Also works with OoT Redux, but with more items.
