### ISSUE TITLE
Feature request: Info on whether the various options will run on real hardware or not

### ISSUE THREAD

**Issue by ifighftdragons** [Admentus64/Patcher64Plus-Tool#59]
Some options for various games - like the 60fps hacks - should let you know if it's hardware compatible or not.

Just put something like this behind options that won't work on real hardware:

*NOT compatible on real hardware

**Comment by Admentus64** [comment]
Won't fix.

But others may attempt to document this. I accept Pull Requests for that.

**Comment by Admentus64** [comment]
Added generic tooltip messages auto-generated based on expected terms for options for v23.1.0. Closing.
