### ISSUE TITLE
Unable to patch Majora's Mask, OOT works fine.

### ISSUE THREAD

**Issue by GitMoDu** [Admentus64/Patcher64Plus-Tool#6]
`Failed! ROM does not match the patching button target. ROM has left unchanged.`

Do I have a corrupted ROM? What can I do?
I can patch the WAD successfully, but in native mode I won't accept.

**Comment by Admentus64** [comment]
You need an proper No-Intro dumped ROM (which can be dumped from the GC disc or the VC WAD for example)

Open Patcher64+ Tool and go into the Checksum tab in the Info / Credits window. You can see if you got a proper and therefore supported ROM.

![Checksum](https://user-images.githubusercontent.com/8747034/100005881-ecd52480-2dc9-11eb-9ade-1387ce16d4db.jpg)

**Comment by GitMoDu** [comment]
Thank you very much, time for dumping then!
