### ISSUE TITLE
Feature Request: Add Support for Ocarina of Time and Majora's Mask GC Versions

### ISSUE THREAD

**Issue by ThomasCapella** [Admentus64/Patcher64Plus-Tool#60]
The Virtual Console versions don't support rumble and it's convenient to have it playable on a Wii. If it's possible this would be a nice feature to have. I've tried injecting a patched Redux rom into Collectors Edition but it crashed on boot every time.

**Comment by Admentus64** [comment]
Won't happen.

Both are a completely different ROM (with different SRAM specifications to account for the GC disc saving) and the GC discs can't have their RAM expanded (required for OoT Redux).
