### ISSUE TITLE
2x Damage Multiplier in Majora's Mask doesn't work[BUG]

### ISSUE THREAD

**Issue by ronin9208** [Admentus64/Patcher64Plus-Tool#61]
Setting the damage multiplier for Majora's Mask (for "Additional Options & Redux") to 2x does not produce the intended result. It actually does the default 1x damage. I tested this with the Skulltula in the Bomber's Hideout by running into it and seeing how much damage I received. In the original version, a hit from a Skulltula produces damage of 1/2 heart. With the 2x damage option, the damage produced is still 1/2 heart, though it should be 1 heart. Oddly, 4x and 8x damage *does* work as intended. 4x produces damage of 2 hearts, and 8x damage makes it a kill.

[2023-01-31.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/10552854/2023-01-31.log)

**Comment by Admentus64** [comment]
I have it fixed with the next update.

**Comment by Admentus64** [comment]
Fixed with v20.0.1
