### ISSUE TITLE
Feature Request: Hold L to levitate

### ISSUE THREAD

**Issue by dragonzord28009** [Admentus64/Patcher64Plus-Tool#62]
Would be great if this could be added as an option :)

This is already a gameshark cheat code but it needs to be turned ON everytime I load up the emulator

**Comment by Admentus64** [comment]
Reasonable enough request. Will be a part of Redux if so.

In due time.

**Comment by Admentus64** [comment]
Added to OoT Redux with v20.1.0.

**Comment by Admentus64** [comment]
Completed with v20.1.0.
