### ISSUE TITLE
[BUG] Mario 64 splitscreen Multiplayer is not up-to-date

### ISSUE THREAD

**Issue by darksapra** [Admentus64/Patcher64Plus-Tool#63]
**Description**
This is a long guess, but I tried patching my mario64 rom with the provided patch. On some emulators, it wasn't working. When I tried the provided by the official Kaze (https://www.youtube.com/watch?v=qR1cLfKLMp4) It worked just fine. Im guessing then that the provided ips patch is not uptodate.

**How to Reproduce**
Patch with ips provided and with ips of Kaze, and results will be diferent

**Expected behavior**
It should run

**Comment by Admentus64** [comment]
Updated with v20.0.2.
