### ISSUE TITLE
Masked Quest patch causes crash

### ISSUE THREAD

**Issue by Ninjaspecs** [Admentus64/Patcher64Plus-Tool#65]
Anytime I select the Masked Quest 4.3 patch under a functioning Majora's Mask rom, upon loading the patched ROM, all that is displayed is a red line in the upper left-hand corner.

To reproduce take a Majora's Mask 1.0 rom, select it and patch, no need to select options.

**Log files**
Please post a log file. You can find it in Files/Logs.
[2023-02-16.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/10762851/2023-02-16.log)
![image_2023-02-16_221322522](https://user-images.githubusercontent.com/125626193/219540369-eeee8b6e-2dc2-4496-b78d-49d20aab0dfd.png)

**Comment by Admentus64** [comment]
ROM seems to crash because it's compressed to 32 MB. Works fine in 64 MB mode. Will investigate later.

**Comment by Admentus64** [comment]
Rolled back to the latest patch found at: https://www.romhacking.net/hacks/3959/

Forced in compressed mode only now. Removed additional options.

v20.0.2.

**Comment by Admentus64** [comment]
Another update with hotfix 2 for v20.0.2.

Using the 4.3 Textpointer Fix again with support for decompression, so that additional options work once more.

An adjusted DMA Table will be forced Masked Quest so that it boots again in compressed 32 MB mode.
