### ISSUE TITLE
Return to Dinosaur Land for Super Mario World (SNES)

### ISSUE THREAD

**Issue by grandosegood** [Admentus64/Patcher64Plus-Tool#66]
hi there, is it possible to add this mod so it can be added into the super mario world wii wad? Thanks.

**Comment by Admentus64** [comment]
Reasonable and simple enough. I have it added with v20.1.0.

**Comment by grandosegood** [comment]
thank you much!

**Comment by Admentus64** [comment]
Completed with v20.1.0.

Wii VC support isn't possible though. Native Mode is supported.
