### ISSUE TITLE
feature request - latest version of hooting time for mario kart 64

### ISSUE THREAD

**Issue by grandosegood** [Admentus64/Patcher64Plus-Tool#67]
hi there, can you please add the latest version of hooting time for mario kart 64 on your next release?
is it possible for me to add it to the app by adding a new entry on the JSON file, or by just renaming the newer bps to the old versions name? thanks.

**Comment by Admentus64** [comment]
I have it updated then.

**Comment by Admentus64** [comment]
Completed with v20.1.0.
