### ISSUE TITLE
[BUG] It don't modify VC Controls OOT

### ISSUE THREAD

**Issue by AleosUnderscore** [Admentus64/Patcher64Plus-Tool#68]
(English is not my native language sorry)

**Description**
Recently updated the patcher and it no longer modify my control mapping for Redux (VC). It keeps vanilla controls all the time (D-Pad = L). I have deleted all patcher's files before downloading the updated version but it don't change anything.  Sorry if i've just done something wrong but i need help

**How to Reproduce**
Remapping VC controls.

**Expected behavior**
Remapped VC controls.

**Log files**
[2023-04-02.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/11130849/2023-04-02.log)

**Comment by Admentus64** [comment]
Fixed with v20.2.4.

Try again.
