### ISSUE TITLE
Windows 7 x64 crash with version 6.1.1.0

### ISSUE THREAD

**Issue by 60fpshacksrock** [Admentus64/Patcher64Plus-Tool#7]
I got this version from gbatemp: https://gbatemp.net/download/all-in-one-wii-vc-injecting-tools-by-saulfabreg.35917/
I noticed the newer versions did not contain an EXE so I couldn't test them.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Patcher64+ Tool.exe
  Application Version:	6.1.1.0
  Application Timestamp:	5f0b3e7d
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24520
  Fault Module Timestamp:	5d673e23
  Exception Code:	e0434352
  Exception Offset:	000000000000b87d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	658e
  Additional Information 2:	658eec355a7393adf2b86e4853eec3fc
  Additional Information 3:	2384
  Additional Information 4:	2384f66368711c39243babc6842437e2

**Comment by Admentus64** [comment]
Don't download it from GBATemp, but from the official GitHub repository (you are already on it). So I will be closing this issue.

1. Version 6.1.1 is outdated. Version 10.0.0 is currently the latest.
2. An .exe hasn't been distributed for a while.
3. Patcher64+ Tool is designed in PowerShell, so you need to have this installed. PowerShell is installed by default on Windows 10, but has to be installed separately on Windows 7 or 8.
4. The distributed .exe back then never worked for Windows 7. Only newer OS versions.



--- Guide to install PowerShell on Windows 7 ---

1) Install Windows Framework .NET 4.5 or above:
https://go.microsoft.com/fwlink/?linkid=2088631

2) Install Windows Management Framework 5.1: 
https://www.microsoft.com/en-us/download/details.aspx?id=54616
* For X86/32bits: Download Win7-KB3191566-x86.zip and run Win7-KB3191566-x86.msu
* For X86_X64/64bits: Download Win7AndW2K8R2-KB3191566-x64.zip and run Win7AndW2K8R2-KB3191566-x64.msu

3) Run PowerShell 5.1 and run $PSVersionTable, you should get this image:
https://media.discordapp.net/attachments/689527363717169277/755328525153730640/unknown.png?width=400&height=293

4) If PowerShell refuses to run Patcher64+ with a message about scripts being disabled on your machine:
* Open PowerShell's terminal as "Run as Administrator" (or run Start-Process powershell -Verb runAs)
* Run Set-ExecutionPolicy -ExecutionPolicy Unrestricted
* Permissions are unlocked now for the whole system

**Comment by 60fpshacksrock** [comment]
Simply installed what you said and got it working. Thanks, and awesome tool by the way.
