### ISSUE TITLE
[BUG] OoT Scene Editor has trouble extracting scenes

### ISSUE THREAD

**Issue by ronin9208** [Admentus64/Patcher64Plus-Tool#70]
**Description**
Extracting scenes for OoT doesn't seem to work properly. The message bar in the bottom left says "Success! The scenes have been extracted." but nothing shows up in the scene editor. I do the same thing with the MM scene editor, and it loads all the actors and objects just fine. I tried two different OoT versions (1.0 and 1.2) and nothing showed up in either case. Furthermore, the log states all maps were wrote to the \Files\Games\Ocarina of Time\Editor\Scenes folder, but the only things I see there are the dungeons (e.g. Hyrule Field is missing). Even then, only the Ura Quest version is there. This may or may not be related, but the bottom right of the window has some radio buttons, but only the "All scenes" one is selectable. I'm not even sure what the other two do because the text does not load properly. 

**Screenshots**
![Scene Editor](https://user-images.githubusercontent.com/124114239/231340850-65896730-508d-4ddf-93a9-7147291c9e3f.png)

**Log files**
[2023-04-11.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/11206790/2023-04-11.log)

**Comment by Admentus64** [comment]
Please update to 20.2.7 first.

**Comment by ronin9208** [comment]
Updating resolved that issue. My apologies for not trying that first. I'm now using 20.2.7, but running into a slightly different problem. Trying to patch scenes results in this error: "Failed! Extracted scenes were missing." Looking at the log, it seems to start fine, but when it comes to patching anything dungeon-related, it then fails. The dungeon scenes are definitely not missing. I can see them all in the scenes directory along with everything else, and the log shows they were extracted properly. I was even able to edit them.

[2023-04-12.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/11217916/2023-04-12.log)

**Comment by Admentus64** [comment]
Confirmed. Has issue with patching in MQ or Ura.

Reopened.
