### ISSUE TITLE
no way to patch remapped vc controls?

### ISSUE THREAD

**Issue by Laqueeshous** [Admentus64/Patcher64Plus-Tool#71]
the option to patch vc controls just isnt there and selecting the options in the patcher does nothing in game. am i doing something wrong?

**Comment by Admentus64** [comment]
More specifics please

**Comment by Admentus64** [comment]
Tested it on v20.3.1 - Hotfix 2 (2023-04-22)

Works fine.

Closing this issue. Will reopen if you can show it's broken.

**Comment by Laqueeshous** [comment]
ok so when i initially posted that i didnt realise the patch vc emulator only button was removed, however what is happening is when i remap the controls and patch the rom, the controls are unedited in game, so i am trying to change the dpad controls for majoras mask redux, and when i boot up the game the dpad is still mapped to the L button like normal, and its not an issue with dolphin because i have the controls mapped normally in there, i will try to record a video of what i am talking about

**Comment by Laqueeshous** [comment]
sorry github wouldnt let me upload video bigger than 10mb so i uploaded them on youtube as unlisted videos here are the links:

screen recording: https://youtu.be/lh3NxUVP0RQ
phone recording: https://www.youtube.com/shorts/Rjryhtrcarg

**Comment by Laqueeshous** [comment]
ok nevermind false alarm, not sure how or why it wouldnt work before but i download your new version of patcher64+ u put up yesterday and tried that one instead and it works perfectly

u can keep the issue closed

**Comment by Admentus64** [comment]
You showed you used v20.2.0 in the video. v20.3.0 was already released when the issue was made.

One of the issues fixed in after v20.2.0 was the VC controls not working.

Please make sure you already use the latest version before opening an issue.

**Comment by Laqueeshous** [comment]
yea thats my fault bro i downloaded it before u released the latest version and i didnt realise there was a new version
