### ISSUE TITLE
[BUG] Reversed eye textures for a few "+ OoT/MM Eyes" Child Link models...

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#72]
**Description**
The "_+ OOT/MM Eyes_" variants of certain **Child Link** models, have their looking at right/left eyes texture reversed.
The problem are in both OOT/MM player model selection.

**How to Reproduce** : 
Just choose one of them and patch them into your rom. Let the player model idling for a few minutes or let a cutscene play : 
**_Example_** - when looking at its right, the eyes textures look at the left and vice versa.

Is there a way to resolve this?

**Comment by GhostlyDark** [comment]
This is not how the eyes work. Looking left also moves the eyes to that direction.

![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/31742919/7d3cd915-c9ff-4b15-88a3-171128780496)

![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/31742919/6532ec7d-522a-483d-af39-6d0bc0243f48)
