### ISSUE TITLE
Fierce Diety Remastered has Glitched Smile Texture

### ISSUE THREAD

**Issue by XModxGodX** [Admentus64/Patcher64Plus-Tool#8]
Probably worth noting that the Modloader64 model has the same issue.
![Glide64_THE_LEGEND_OF_ZELDA_38](https://user-images.githubusercontent.com/22751086/103350865-3a425280-4a56-11eb-9935-6231fbb61dbc.png)

**Comment by Admentus64** [comment]
Thanks for the report.

I either remove the model or attempt to fix it. In case it's getting removed, there's still the Fierce Deity Model from Majora's Mask. That model works pretty well.

**Comment by Admentus64** [comment]
Fixed with the removal of the model in v10.0.1. The model didn't live up to the quality standard Patcher64+ aims for.

The remaining Fierce Deity model should be sufficient. It has no issues and is ported from Majora's Mask directly.
