### ISSUE TITLE
Feature Request : Alt Link icon for the dungeon subscreen of OOT

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#80]
It's a little thing that I thought about the vanilla dungeon map icons : The **OOT** Link icon is... fugly. I don't want to be rude to **Nintendo** though, it just looks weird...

But I do not want to change every icons with the MM ones, so...

I don't know if you take contributions or proposed features, but I quickly did a doodle :

https://drive.google.com/file/d/129BzZPqxgwDSSXCcX2tnxmfQ1zIILNwg/view?usp=sharing

- It's a fusion of the **MM** Link icon with the **OOT** one, so now, it looks shaded like the other icons and you wouldn't need to change them all anymore. Just this specific one. All in vanilla resolution.

It would be named _**"Alt Link Icon"**_ and be in the **Graphics** tab.

Let me know if you want to do something with it in a future release.

**Comment by GoldenMariaNova** [comment]
By the way, as a side comment, from all the games Patcher64+ can patch and/or fix, MM and OOT seems to be the biggest and largest ones to patch and fix.

That's why I often propose stuff for them, as the others seems quite fine actually.

**Comment by Admentus64** [comment]
Drive link doesn't work.

**Comment by GoldenMariaNova** [comment]
> Drive link doesn't work.

It should be now. Try it.

**Comment by GhostlyDark** [comment]
I like it a lot. Admentus is going to throw it into the Patcher asap.

**Comment by Admentus64** [comment]
To be included with v21.1.0.

**Comment by GoldenMariaNova** [comment]
> To be included with v21.1.0.

Thanks for using my custom texture.

**Comment by Admentus64** [comment]
Completed with v22.0.0.
