### ISSUE TITLE
Feature Request : Fixed MM Young Link + OOT Eyes & New MM Adult Link + OOT Eyes (CANCELLED)

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#82]
**_PLEASE DELETE THIS REQUEST._**

**Comment by Admentus64** [comment]
No access to the ZIP file

**Comment by GoldenMariaNova** [comment]
The link has been repaired.

**Comment by Admentus64** [comment]
I suggest that the Hylian Shield texture inject is part of the dedicated Hylian Shield option instead instead of being part of a custom model. The change is too minimum for it to be it's own custom model and whenever content can be modular we prefer that.

I belief we already have a custom model with the OoT eyes for the MM Young Link in OoT. So the only thing missing to add would be the OoT Eyes for Skilar's MM Adult Link.

I can't and I won't restrict users in any way that would require to use both models as once (if we would add them as suggested). That goes against the tool's concept. Users should be free to use any child and any adult model they wish for. That means options would have to work independently from the chosen models. As such no options can be added that can only be applied when a specific set of models is chosen. If I understood correctly what it is you're aiming for in the provided readme.

This is just my view on it though. I rather not accept changes if they aren't compatible with other options or non-modular, as it goes against the concept of the patcher. I'm not perse against this, but I have my hesitations with the restrictions that were brought up. Ultimately it comes down to if these changes are large enough to validate adding a new custom model, as otherwise we would have a bloat of endless minor adjusted models.

Dunno what GhostlyDark thinks of it though. Our official Discord server might be a better place for discussion and features that require discussions: : https://discord.gg/P22GGzz

**Comment by GoldenMariaNova** [comment]
> I suggest that the Hylian Shield texture inject is part of the dedicated Hylian Shield option instead instead of being part of a custom model. The change is too minimum for it to be it's own custom model and whenever content can be modular we prefer that.
> 
> I belief we already have a custom model with the OoT eyes for the MM Young Link in OoT. So the only thing missing to add would be the OoT Eyes for Skilar's MM Adult Link.
> 
> I can't and I won't restrict users in any way that would require to use both models at once (if we would add them as suggested). That goes against the tool's concept. Users should be free to use any child and any adult model they wish for. That means options would have to work independently from the chosen models. As such no options can be added that can only be applied when a specific set of models is chosen. Locking options under certain conditions is poor interface design as it can be confusing for the user what these conditions are, even if tooltips were provided. I know we still have a lot of condition restricted options overall, but my goal is to completely remove/rework/replace those with globally available solutions as much as it allows for officially created Nintendo content. If I understood correctly what it is you're aiming for in the provided readme.
> 
> This is just my view on it though. I rather not accept changes if they aren't compatible with other options or non-modular, as it goes against the concept of the patcher. I'm not perse against this, but I have my reservations with the restrictions that were brought up. Adding dedicated options for vanilla models is fine, because those are official. I am against dedicated options for custom models. Because those are custom and not official. Ultimately it comes down to if these changes are large enough to validate adding a new custom model, as otherwise we would have a bloat of endlessly minor adjusted models.
> 
> Dunno what GhostlyDark thinks of it though. Our official Discord server might be a better place for features that require discussion: https://discord.gg/P22GGzz, so feel free to join up and request features with lengthier discussions. It would be easier to clarify matters in there, and see what the best approach is. As I said, not against it, just reservations.

**Comment by GoldenMariaNova** [comment]
You know what? Let me think of something else instead...

**Comment by GoldenMariaNova** [comment]
> I suggest that the Hylian Shield texture inject is part of the dedicated Hylian Shield option instead instead of being part of a custom model. The change is too minimum for it to be it's own custom model and whenever content can be modular we prefer that.
> 
> I belief we already have a custom model with the OoT eyes for the MM Young Link in OoT. So the only thing missing to add would be the OoT Eyes for Skilar's MM Adult Link.
> 
> I can't and I won't restrict users in any way that would require to use both models at once (if we would add them as suggested). That goes against the tool's concept. Users should be free to use any child and any adult model they wish for. That means options would have to work independently from the chosen models. As such no options can be added that can only be applied when a specific set of models is chosen. Locking options under certain conditions is poor interface design as it can be confusing for the user what these conditions are, even if tooltips were provided. I know we still have a lot of condition restricted options overall, but my goal is to completely remove/rework/replace those with globally available solutions as much as it allows for officially created Nintendo content. If I understood correctly what it is you're aiming for in the provided readme.
> 
> This is just my view on it though. I rather not accept changes if they aren't compatible with other options or non-modular, as it goes against the concept of the patcher. I'm not perse against this, but I have my reservations with the restrictions that were brought up. Adding dedicated options for vanilla models is fine, because those are official. I am against dedicated options for custom models. Because those are custom and not official. Ultimately it comes down to if these changes are large enough to validate adding a new custom model, as otherwise we would have a bloat of endlessly minor adjusted models.
> 
> Dunno what GhostlyDark thinks of it though. Our official Discord server might be a better place for features that require discussion: https://discord.gg/P22GGzz, so feel free to join up and request features with lengthier discussions. It would be easier to clarify matters in there, and see what the best approach is. As I said, not against it, just reservations.

Well I'm doing something more akin of that anyways, plus, I will do better next time.

I will change the request soon.

**Comment by Admentus64** [comment]
Yes. There's a reported issue for the broken eyes already. Haven't looked into it yet. Further discussion regarding that goes into it's respective issue.

I look at the zip folder previously, but not much I can do with it. I am not particular interested in editing models myself so I am probably going to leave this as it is, but we do accept models. You would need to compile the model yourself, generate a patch for it and make a Pull Request for it on the respective repo as this is not something I am going to do myself.

The Hylian Shield option only works on custom models (and the original models) that have the original texture for the Hylian Shield. Different models such as Skilar's Adult Link model use a different codec for the Hylian Shield textures, so the option isn't compatible. There is no interest in adding options unique to custom models.

**Comment by GoldenMariaNova** [comment]
> snips

OK then. I now know how everything of this work and rules now. Sorry for bothering you.

This subject will never be brought again, until I made it myself or did collab with.

If you can, delete this request. After all, it was just an idea.

**Comment by Admentus64** [comment]
Oh... Ok.
