### ISSUE TITLE
[BUG] Strange behaviour on v22.0.0

### ISSUE THREAD

**Issue by ngmoviedo** [Admentus64/Patcher64Plus-Tool#83]
**Description**
In Majora's Mask for N64, Link seems able to climb almost every wall or door, although he falls almost immediately.
Also, widescreen patch doesn't seem to apply correctly.
This issues didn't occur in the previous release.

**How to Reproduce**
1. Patch the rom using default settings (clicking "reset options").
2. Open the rom with Project 64. I'm using [Rosalie's Better Majora's Mask Installer cofiguration](https://github.com/Rosalie241/BetterMajorasMaskInstaller).
3. The behaviour is identical when checking the advanced widescreen option.

**Expected behavior**
Link shouldn't attempt to climb every surface and widescreen patch should apply correctly.

**Screenshots**
[Example](https://github.com/Admentus64/Patcher64Plus-Tool/assets/61010998/a379a7ca-7e9a-4b29-bda2-03c322091ec4)

**Log files**
[2023-09-24.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/12707630/2023-09-24.log)

**Comment by Admentus64** [comment]
Fixed with hotfix 3.
