### ISSUE TITLE
[BUG] Wrong alpha tile for Options Menu from Redux combined with the MM Pause Screen option (Language tab)

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#87]
**Description**
Well, apparently this alpha issue occurred again when patching the MM Style Menu option:
![271338964-eba89b19-f771-40ed-b8d3-f30a9208e523](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/1fc4114f-4d36-40f0-9003-770f02546ae5)
The rest is fine, but it's the L Redux options that have it now. _Yeah_.

I apologize if it's seems like spamming bug issues.

**Comment by Admentus64** [comment]
I look into it later today.

**Comment by Admentus64** [comment]
![image](https://github.com/Admentus64/Patcher64Plus-Tool/assets/8747034/46514068-36d8-4080-a52a-44c729effe7c)
Looks fine to me?

**Comment by GoldenMariaNova** [comment]
> ![image](https://user-images.githubusercontent.com/8747034/271407348-46514068-36d8-4080-a52a-44c729effe7c.png) Looks fine to me?

I meant when you patch **mm_pause_screen.ppf**, it does that. It means another alpha issue for it.

**Comment by Admentus64** [comment]
I see...

GhostlyDark will have to fix that. Like before, I am not going to touch this. I leave this issue open in case GhostlyDark decides to fix this as well.

**Comment by GoldenMariaNova** [comment]
> I see...
> 
> GhostlyDark will have to fix that. Like before, I am not going to touch this. I leave this issue open in case GhostlyDark decides to fix this as well.
> 
> It was always like this btw. I didn't get broken or anything. Seems like the MM Pause Screen uses a different alpha than the OoT one does... 🤔

Well, thanks.

**Comment by GhostlyDark** [comment]
Forgot the Game Over exclusive tile with no text, which is reused for the Redux menu. Fixed via f6358714c71fef02ff2a55d314117862ac664be9.

**Comment by GoldenMariaNova** [comment]
> Forgot the Game Over exclusive tile with no text, which is reused for the Redux menu. Fixed via [f635871](https://github.com/Admentus64/Patcher64Plus-Tool/commit/f6358714c71fef02ff2a55d314117862ac664be9).

Tested. Everything is fixed now. Thank you.
