### ISSUE TITLE
[Feature Request] "Censor Gerudo Textures" replacement for Iron Knuckles

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#88]
For context, the **Gateway** (**Lodgenet**) version of OOT had certain features others did not.

And according to :

https://tcrf.net/The_Legend_of_Zelda:_Ocarina_of_Time/Version_Differences ,

In the **_Crescent and Star_** section, it says that the symbol on the armor of the **Iron Knuckle** was also changed and was supposed to be in in the later iterations of the original **OOT**, but apparently only the **MM** was kept. It seems that they reverted the former one by accident.

For reference, here's the untouched one : 

_**OOT 1.0**_ :
![latest](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/55686ceb-4adf-42db-8963-630e8cda3136)

**_MM 1.0_** : 

![latest_2](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/82b0a9b1-935a-4654-b90d-fd05a6d5f697)

And finally, what it would looks like with via the **_hires_texture_** folder: 

![GLideN64_THE_LEGEND_OF_ZELDA_006](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/40b69bf0-cbf6-4aaa-8574-5360b90492dd)

It would be nice to basically patch this along with the substantial censored **Gerudo** textures, making it basically complete (I checked Dampé's grave again and all symbols are patched now).

So, there's this : https://drive.google.com/file/d/12YOH6oCnQT8N3Zif6-HW4vf52TeCZIwS/view?usp=drive_link

All it needs is to be converted to a .bin file.

I hope all of this can help.

**Comment by Admentus64** [comment]
Maybe 🤔

**Comment by GhostlyDark** [comment]
Done via 04184dd04f871e314393440cc4456ab9c96a3c9a. Part of the `Censored Gerudo Textures` option. 1:1 port of the MM texture, no new inject.
