### ISSUE TITLE
Freeze with Red Bar at top left of screen 

### ISSUE THREAD

**Issue by 765Craven** [Admentus64/Patcher64Plus-Tool#89]
![Screenshot 2023-10-01 212231](https://github.com/Admentus64/Patcher64Plus-Tool/assets/145936939/792dc333-ce39-4fcf-bbc4-25f96b1f83db)
This is occuring in Majora's Mask. This occurs in a couple of situations, but the only one that I've been able to consistently replicate is completing the Dog Race. Every single time, no matter what. I used the setting that makes the Gold Dog always win when setting this patched ROM up, which I'm figuring is the cause, but I'm not certain.
After reloading a save and making my way back to the Dog Race it began occuring just from bringing the lady a dog to engage the race.

**Comment by Admentus64** [comment]
Without a cause this can not be addressed.

Closing.

I re-open it when a cause is known.
