### ISSUE TITLE
[FEATURE] GC Scheme with specific GC text for the C Buttons and the Rumble feature

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#91]
**Is your feature request related to a problem? Please describe.**
Well basically, I find the **GC scheme** to be almost perfect, excepted for the text.
It still mentions **"press"**, the **C** as _**"buttons"**_ and the **Rumble Pak**, and since I play with a modern
_**GC**-like_ controller, it looks awkward.

**Additional context**
If this one request is accepted, maybe **MM** could have one too someday. So, that's it for now.

**Comment by Admentus64** [comment]
Looks like a job for the text editor. Easy.

**Comment by GoldenMariaNova** [comment]
> snips

It's more complicated than that, as some dialogues are almost completely different, like some tutorials being re-written to not cause text overflow and others adjustments.

I also tried the **"ID: original -> new"** thing and it's impossible to do that, as some text have multiple inputs and changed sentences within a same **Message ID**, making this futile.

To clarify, I said that it will be compatible with _**"GC Scheme"**_, but as a separate option.

It truly needs its own separate, alternative _**"Restore Text"**_ **.IPS** option. I am very sorry for that.

Guess it's either that or nothing.

**Comment by GoldenMariaNova** [comment]
> snips

Also, my English needs some work, so excuse the lack of context or wrong explanation.

**Comment by Admentus64** [comment]
I think you misunderstood something.

I am only asking for which changes you like too see. Write them in plain text in this issue like "ID: Original -> ID". I didn't ask for anything else.

I take care of the code and how it actually is implemented.

**Comment by Admentus64** [comment]
Anyway, I just punched in those IDs for OoT using the GC Scheme option for v22.0.4 hotfix 1.

Please try it out. I close the issue once then.

**Comment by GhostlyDark** [comment]
To put it in other words, Admentus is referring to some sort of Text Editor API that exists for the Patcher, which can look like this:

```
SetMessage -ID "0337" -Text 'Hole of "Z"' -Replace 'Hole of "L"'
```

With this, text can be changed programmatically, preserving compatibility with more than just the vanilla text, meaning it can be combined with Restore Text, Female Pronouncs, etc. This is preferred over injecting binary files, because of the mentioned flexibility. The Scene Editor has also an API like this.

**Comment by GoldenMariaNova** [comment]
> Anyway, I just punched in those IDs for OoT using the GC Scheme option for v22.0.4 hotfix 1.
> 
> Please try it out. I close the issue once then.

_Well,_ 
![Untitled](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/5daed200-7f5f-4a44-914f-eba768467948)

This is awkward.

**Comment by GoldenMariaNova** [comment]
> snips

I'm aware of these, as the female pronouns and Easter eggs uses these same API codes.

**Comment by Admentus64** [comment]
Ehh. I fix it. No worried.

I didn't really test it. My bad.

I try again properly tomorrow.

**Comment by GoldenMariaNova** [comment]
> Ehh. I fix it. No worries.
> 
> I didn't really test it. My bad.
> 
> I try again properly tomorrow.

Truly sorry to make you go through this coding hell.

**Comment by Admentus64** [comment]
Ehh. It's bo biggie.

I do this for fun and out of curiosity.

It's not hard. I was just a bit too lazy and quick with the commit. My bad.

**Comment by GoldenMariaNova** [comment]
> Ehh. It's no biggie.
> 
> I do this for fun and out of curiosity.
> 
> It's not hard. I was just a bit too lazy and quick with the commit. My bad.

You know, actually, let me fork Ocarina of time.psm1. I got a great hang of what it must be done and be corrected. I will do that myself instead.

**Comment by GoldenMariaNova** [comment]
> snips

Please check your **pull requests** when you have the time.

**Comment by Admentus64** [comment]
I am aware yes.

I am just not merging any requests while a sleep.

I leave this issue open until MM is covered too.

**Comment by GoldenMariaNova** [comment]
> Please check your **pull requests** when you have the time.

Please check your pull requests again. The **MM** one is done too.

**Comment by Admentus64** [comment]
Can't accept yet. Issues have to be resolved first.

**Comment by GoldenMariaNova** [comment]
> Can't accept yet. Issues have to be resolved first.

Fixed. It was a just a rookie mistake. Should work now. With this, it should be done for good.

**Comment by Admentus64** [comment]
Completed.
