### ISSUE TITLE
[BUG] OOT crash on startup since a certain update

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#93]
**Description**
If any actor-based settings is checked in the patcher, when the ROM have finished patching, OOT crashes on any emulator startup.

**How to Reproduce**
Simply check "remove owls" option for example.

**Expected behavior**
Well, to not crash on emulation start up.

**Additional Notes**
I think this have something to do with this commit : https://github.com/Admentus64/Patcher64Plus-Tool/commit/bff3ad990b0b695bae63983d2b7a2e7cf743f827

That's all.

**Comment by Admentus64** [comment]
Owls are being removed. Not added. So that commit has nothing to do with it.

**Comment by Admentus64** [comment]
Found the issue already. Header map offsets aren't properly adjusted. Size effect of no longer shifting the maps.

**Comment by Admentus64** [comment]
Should be fixed again with hotfix 6. I accidentally broke scene patching by introducing new API functions.
