### ISSUE TITLE
[BUG]A patching problem with Censored Gerudo Textures

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#96]
**Description**
According to the console,
![Untitled](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/859f5a04-096c-4e76-b030-7e50fe0c26b5)

resulting in this being unpatched:

![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/5054b6fc-92a6-4126-8598-6d89c78d570d)

Seems to be a problem with the scene editor not finding the offset of the specific map or not finding the name of the latter.

**How to Reproduce**
Simply select _**"Censor Gerudo Textures"**_.

The rest works fine though.

**Update** : Fixed with https://github.com/Admentus64/Patcher64Plus-Tool/pull/95

**Comment by Admentus64** [comment]
Yes. I am aware it happened. I pushed some fixes, and forgot to update the name.

There's no need to make an issue if you already made a Pull Request for it. Just the Pull Request suffices.

**Comment by GoldenMariaNova** [comment]
> snips

It's done.
