### ISSUE TITLE
Feature Request : Updated Alt Link Dungeon icon - Now with a New Boss Skull Icon And a Non-Link Icon Too!

### ISSUE THREAD

**Issue by GoldenMariaNova** [Admentus64/Patcher64Plus-Tool#98]
I basically updated the **Alt Link** icon texture, along with a new skull boss icon to go with it now.

Why the skull one now? Well, with some further observations, the original looks like this : ![THE LEGEND OF ZELDA#7F579284#0#2_all](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/d7bfb8f2-2b69-4d72-bf85-b1fb66107c20) .
It especially looks awkward when "**MM Pause Screen**" or the "**Files Icons**" is enabled.

I don't know why the original's middle mouth is transparent, but regardless, here what the new one will looks like: ![THE LEGEND OF ZELDA#7F579284#0#2_all](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/ade80ff8-d32d-4c0a-b361-9fcd4c4693a6) .

.

So, it has been modified a little (There's was also an white halo glitch) and the mouth is now full. Also, the added yellow pupils, is to make a fusion between **OOT** & **MM**, like how the **Link** one was designed.

Files : https://drive.google.com/file/d/12_usqGuiwj6v4E2u_0RG1B6laIezXrUI/view?usp=drive_link

P.S. : There's also a generic **Triforce** Icon for non-**Link** players models now : ![18493-200](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/8bfff1cb-e9b0-43b8-afc9-fff1b6456991) .

This one should be called... well, "**Triforce**", and combined with the skull too. For the final touch, they have now a subtle drop shadow effect, making these almost looks official.

That's it for now. As for Oct. 25, the .zip file should be finalized. 

Here's a preview of what they should looks like (excluding the ![THE LEGEND OF ZELDA#C7911273#0#2_all](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/e975f466-9e69-46b9-aef7-61fb79fdb1b0) one, which have the same effect anyways) : 

![GLideN64_THE_LEGEND_OF_ZELDA_000](https://github.com/Admentus64/Patcher64Plus-Tool/assets/132231190/2891fde0-4b24-4a56-a4b7-5d3936e4f533)

**Comment by GoldenMariaNova** [comment]
> snips

By the way, do update the option only when you have the time, as you seems to be for the big Overhaul update soon.

**Comment by Admentus64** [comment]
Will be looked at eventually. Looks fine enough.

**Comment by GoldenMariaNova** [comment]
> snips

By the way, if you have downloaded the zip, re-download it again, as I retouched the icons.

Otherwise, disregard that.

**Comment by GoldenMariaNova** [comment]
> snips

By the way, if you have downloaded the zip, I insist you re-download it again, as I retouched the icons.

Otherwise, disregard that.

**Comment by GoldenMariaNova** [comment]
> snips

Do the request still stand?

**Comment by Admentus64** [comment]
I haven't forgotten about it. Just didn't get to it yet. Working on other features at the time being.

**Comment by Admentus64** [comment]
Completed with v23.1.0.
