### ISSUE TITLE
[BUG] Winning at Shooting Gallery causes a crash

### ISSUE THREAD

**Issue by Thirteen1355** [Admentus64/Patcher64Plus-Tool#99]
**Description**
When hitting the final Rupee in the Shooting Gallery minigame, the game crashes. Tested with vanilla in the same emulator, which produced no issues. 

**How to Reproduce**
Go to the Shooting Gallery in Hyrule Castle Town and hit all the Rupees that appear. Upon hitting the last Rupee, the game crashes outright. It happens everytime. 

**Expected behavior**
Static shows up on the screen (not sure if this is an emu-specific thing) and the game stays this way on windowed. On fullscreen, the emulator closes itself (CTD). 

**Screenshot**
![Untitled](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/a2166ad5-91fb-4104-b512-f5b5b7ed5a6c)

**Video**
https://youtu.be/_i_4JSWOU1s?feature=shared

**Settings**
No. I uploaded a video, though. I will instead upload screenshots with all my settings. 
![Patcher1](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/510dfee1-e495-458f-a7a8-c513b1fe7b48)
![Patcher2](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/eb78a838-dd02-4d90-82e0-6050bfd9e94e)
![Patcher3](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/caf5919b-dd5b-4b7f-8c57-06efef4c833f)
![Patcher4](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/ae696608-3509-4364-846f-7c69492067c3)
![Patcher5](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/29f63a9f-7c52-4e53-9576-35f35a151188)
![Patcher6](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/8856d1cc-47dd-40ed-97d1-fc13a9886020)
![Patcher7](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/2109e936-d988-4b11-bbcf-ea954a95fcb9)
![Patcher8](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/38f838ba-eba8-4c64-8424-8218bbde6568)
![Patcher9](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/de75ac5d-b7f5-4cee-86c7-9c6a0939dc45)
![Patcher10](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/34cbf7f1-d763-4b0c-a2d6-ed674d19df41)
![Patcher11](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/108cc43e-1421-440b-a5d2-77669e410af6)
![Patcher12](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/8d14e4c0-d0a4-40b2-ade1-8d40c17f552f)
![Patcher13](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/757e0acb-e9e5-4dcb-9133-46f45a2b3406)
![Patcher14](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/071447a4-aa99-46a1-8c30-23281e0a39b2)
![Patcher15](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/b327512d-f3c6-4575-ad06-506fc7455861)
![Patcher16](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/2b22da1f-fad9-405f-a5d0-fa3f0c826457)
![Patcher17](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/767f16f1-03c1-4f1d-a9ad-39234b02e794)
![Patcher18](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/d7177b7d-bc5c-418c-b7a0-ebb50398f433)
![Patcher19](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/7748099c-83db-4ac9-a2d0-82968fc16559)
![Patcher20](https://github.com/Admentus64/Patcher64Plus-Tool/assets/71778203/b50a81d2-180f-4f6f-83a7-479b5f987bb3)

**Logs**
[2023-10-16.log](https://github.com/Admentus64/Patcher64Plus-Tool/files/13033002/2023-10-16.log)

**Comment by Admentus64** [comment]
Log file is missing.

Share please.

**Comment by Thirteen1355** [comment]
> Log file is missing.
> 
> Share please.
> 
> Patcher version is also out of date. Reconfirm on newest version. No support for older versions.
> 
> If the issue still persists, start with disecting which option causes the crash. I have it fixed then once there is a clear known cause.

Added log file but will update version now and try to reproduce.
